import type {AdaptedDesignConstraints, BrandIntelligenceSession} from '../brand-intelligence/index.js';
import type {AIUsageResult} from '../../infrastructure/ai/types.js';
import type {ReferenceIntelligenceSession} from '../../application/reference-intelligence/index.js';

export const CREATIVE_DIRECTION_SCHEMA_VERSION = '1.0.0' as const;
export type CommunicationObjective = 'awareness'|'consideration'|'conversion'|'promotion'|'product_launch'|'education'|'trust'|'retention'|'announcement'|'event'|'brand_building'|'other';
export interface SourcedFact<T> {value: T; source: 'explicit'|'inferred'; confidence: number}
export interface AudienceContext {market?: string; country?: string; language?: string; industry?: string; role?: string; familiarity?: string; intent?: string}
export interface MessageHierarchyItem {role: 'hook'|'headline'|'subheadline'|'benefit'|'offer'|'proof'|'data'|'cta'|'legal'|'support'; contentReference: string; priority: number; visualImportance: number; confidence: number}
export interface CommunicationBrief {objective: SourcedFact<CommunicationObjective>; desiredAudienceResponse: SourcedFact<string>; desiredAction?: SourcedFact<string>; singleMindedProposition: SourcedFact<string>; primaryMessage: SourcedFact<string>; secondaryMessages: SourcedFact<string>[]; offer?: SourcedFact<string>; proofPoints: SourcedFact<string>[]; mandatoryContent: SourcedFact<string>[]; cta?: SourcedFact<string>; category?: SourcedFact<string>; audienceContext?: AudienceContext; tone: string; explicitFacts: string[]; inferredFacts: string[]; uncertainties: string[]; confidence: number}
export interface CreativeStrategicFrame {communicationProblem: string; communicationOpportunity: string; singleMindedProposition: string; desiredResponse: string; messageHierarchy: MessageHierarchyItem[]; brandRole: string; referenceRole: string; formatRole: string; creativeOpportunity: string; confidence: number}
export interface CreativeTension {poleA: string; poleB: string; resolution: string; relevance: string; confidence: number}
export interface CreativeTerritory {name: string; logic: string; relevance: string; confidence: number}
export interface VisualThesis {dominantElement:string;dominanceReason:string;memorabilityMechanism:string;communicatingRelationship:string;brandRecognition:string}
export interface CreativeConcept {name: string; coreIdea: string; strategicRationale: string; visualThesis: VisualThesis; audienceTakeaway: string; brandRelevance: string; communicationRelevance: string}
export interface VisualMetaphor {concept: string; literalness: number; relevance: number; originality: number; executionRisk: number; confidence: number}
export interface CreativeDevice {name: string; description: string; communicationFunction: string; brandConnection: string; repeatability: number; distinctiveness: number; productionFeasibility: number}
export interface CreativeDivergenceVector {abstraction:number;humanFocus:number;productFocus:number;editoriality:number;dynamism:number;minimalism:number;dimensionality:number;narrativeDepth:number;typographicExpression:number}
export interface FormatAdaptability {score:number;strengths:string[];risks:string[];adaptationNotes:string[]}
export interface ImageStrategy {mode:'photography'|'illustration'|'3d'|'abstract'|'mixed'|'none';subjectRole:string;framingCharacter:string;lightingCharacter:string;backgroundCharacter:string;authenticity:string;depthCharacter:string;retouchingCharacter:string}
export interface TypographyBehavior {typographicRole:string;scaleContrast:string;density:string;expressiveness:string;alignmentCharacter:string;headlineBehavior:string;dataBehavior:string}
export interface ColorBehavior {dominance:string;accentBehavior:string;contrast:string;coverageLogic:string;backgroundRole:string;foregroundRole:string;tokenPolicy:string}
export interface SpatialStrategy {density:string;negativeSpaceRole:string;visualBreathing:string;layering:string;compression:string;expansion:string;rhythm:string}
export interface MaterialStrategy {required:boolean;characters:string[];conceptualRole:string}
export interface RouteProvenance {decision:string;source:'communication_strategy'|'reference_structure'|'brand_hard_constraint'|'brand_soft_preference'|'brand_distinctive_asset'|'adaptation'|'creative_concept'|'creative_device'|'format'|'execution_interpretation';confidence?:number}
export interface ArtDirectionRoute {id:string;internalName:string;territory:CreativeTerritory;concept:CreativeConcept;strategicRationale:string;creativeTension?:CreativeTension|null;visualMetaphor?:VisualMetaphor|null;creativeDevice:CreativeDevice;heroStrategy:'product'|'human'|'typography'|'data'|'symbolic_object'|'graphic_device'|'mixed'|'none';compositionStrategy:string;hierarchyStrategy:string;typographyBehavior:TypographyBehavior;colorBehavior:ColorBehavior;imageStrategy:ImageStrategy;shapeStrategy:string;materialStrategy:MaterialStrategy;textureStrategy:string;spatialStrategy:SpatialStrategy;graphicDeviceStrategy:string;narrativeBehavior:string;copyHierarchy:MessageHierarchyItem[];brandExpression:string;referencePrinciplesUsed:string[];adaptationActionsUsed:string[];distinctiveAssetsUsed:string[];antiClicheStrategy:string[];antiAiStrategy:string[];formatAdaptability:FormatAdaptability;productionFeasibility:number;divergenceVector:CreativeDivergenceVector;confidence:number;provenance:RouteProvenance[];declaredHardViolations?:string[];inventedClaims?:string[];literalReferenceTraits?:string[];declaredBrandDriftTraits?:string[]}
export interface CreativeRouteEvaluation {routeId:string;communicationFit:number;brandFit:number;constraintCompliance:number;distinctiveness:number;referenceTransformation:number;formatFit:number;productionFeasibility:number;visualSophistication:number;antiAiDiscipline:number;originality:number;routeBrandDriftRisk:number;routeReferenceImitationRisk:number;weightedScore:number;eligible:boolean;gateFailures:string[]}
export interface CreativeDirectionQuality {strategicCoherence:number;routeDiversity:number;brandIntegrity:number;referenceTransformation:number;creativeDistinctiveness:number;constraintCompliance:number;overall:number}
export interface CreativeDirectionRequest {projectId:string;copy:string;format:string;destinationTool:string;tone:string;communicationObjective?:CommunicationObjective;audienceContext?:AudienceContext;brandIntelligence?:BrandIntelligenceSession;referenceIntelligence?:ReferenceIntelligenceSession;adaptedDesignConstraints?:AdaptedDesignConstraints;existingSession?:CreativeDirectionSession}
export interface CreativeRouteCandidateSet {strategicFrame:CreativeStrategicFrame;routes:ArtDirectionRoute[]}
export interface CreativeDirectionSession {schemaVersion:typeof CREATIVE_DIRECTION_SCHEMA_VERSION;sessionId:string;projectId:string;createdAt:string;inputFingerprint:string;communicationBrief:CommunicationBrief;strategicFrame:CreativeStrategicFrame;routes:ArtDirectionRoute[];evaluations:CreativeRouteEvaluation[];selectedRouteId?:string;selectedRoute?:ArtDirectionRoute;status:'ready'|'partial'|'failed';failureReason?:'no_eligible_route'|'insufficient_divergence'|'generation_failed';quality:CreativeDirectionQuality;warnings:string[];aiUsage?:AIUsageResult;cost?:number;sourceVersions:{referenceSession?:string;brandSession?:string;creativeSchema:string}}
export interface CreativeRouteGenerator {generate(input:{brief:CommunicationBrief;request:CreativeDirectionRequest}):Promise<CreativeRouteCandidateSet>}
