import express from 'express';
import {loadOpenAIConfig} from '../infrastructure/ai/providers/openai/config.js';
import {createLegacyAIRouter} from './api/legacy-ai.js';
import {createVisualForensicsRouter} from './api/visual-forensics.js';
import {createCreativeDirectionRouter} from './api/creative-direction.js';
import {applicationBudgetStore} from '../infrastructure/ai/budget/runtime-store.js';
import {createLayoutRouter} from './api/layout.js';
import {createArtDirectorReviewRouter} from './api/art-director-review.js';
import {createRenderRouter} from './api/render.js';
import {createImageAssetsRouter} from './api/image-assets.js';
import {applicationGeneratedAssetStore} from '../infrastructure/image-generation/index.js';
import {createVisualQaRouter} from './api/visual-qa.js';
import {createExportsRouter} from './api/exports.js';
import {applicationProductionArtifactStore} from '../infrastructure/export-engine/index.js';

export const createServerApp = () => {
  const config = loadOpenAIConfig();
  const app = express();
  app.use(express.json({limit: `${config.maxImageMb + 1}mb`}));
  app.get('/api/health', (_request, response) => response.json({status: 'ok', service: 'picadesigner-api'}));
  app.get('/api/health/ai-budget',async(_request,response)=>response.json(await applicationBudgetStore.health()));
  app.get('/api/health/asset-store',async(_request,response)=>response.json(await applicationGeneratedAssetStore.health()));
  app.get('/api/health/export-store',async(_request,response)=>response.json(await applicationProductionArtifactStore.health()));
  app.use('/api/visual-forensics', createVisualForensicsRouter());
  app.use('/api/creative-direction', createCreativeDirectionRouter());
  app.use('/api/layout', createLayoutRouter());
  app.use('/api/art-director',createArtDirectorReviewRouter());
  app.use('/api/render',createRenderRouter());
  app.use('/api/assets',createImageAssetsRouter());
  app.use('/api/visual-qa',createVisualQaRouter());
  app.use('/api/exports',createExportsRouter());
  app.use('/api/ai', createLegacyAIRouter());
  return app;
};
