import {POST_RENDER_REVIEW_SCHEMA_VERSION,type PostRenderIssue,type PostRenderVisualQaProvider,type PostRenderVisualReview,type VisualQaTarget} from '../../domain/post-render-review/index.js';
export type MockQaScenario='approved'|'notes'|'hand_failure'|'text_contamination'|'logo_contamination'|'watermark'|'layout_issue'|'low_confidence'|'sol_escalation'|'regeneration_success'|'regeneration_failure';
export class MockPostRenderVisualQaProvider implements PostRenderVisualQaProvider{
  readonly id='mock';readonly calls:Array<{targetIds:string[];checksums:string[];byteLengths:number[]}>=[];
  constructor(private readonly scenario:MockQaScenario='approved'){}
  async review(targets:VisualQaTarget[]):Promise<PostRenderVisualReview>{
    this.calls.push({targetIds:targets.map(target=>target.id),checksums:targets.map(target=>target.checksum),byteLengths:targets.map(target=>target.bytes.length)});
    const target=targets.find(item=>item.type==='generated_asset')??targets[0];if(!target)throw new Error('No QA target.');
    const map:Partial<Record<MockQaScenario,{owner:PostRenderIssue['owner'];domain:string;diagnosis:string;severity:PostRenderIssue['severity']}>>={hand_failure:{owner:'asset_generation',domain:'anatomy',diagnosis:'Deformed hand anatomy.',severity:'major'},text_contamination:{owner:'asset_generation',domain:'content',diagnosis:'Invented text-like glyphs.',severity:'major'},logo_contamination:{owner:'asset_generation',domain:'content',diagnosis:'Invented brand-like mark.',severity:'blocker'},watermark:{owner:'asset_generation',domain:'content',diagnosis:'Watermark detected.',severity:'blocker'},layout_issue:{owner:'layout',domain:'layout',diagnosis:'Text block overlaps CTA.',severity:'major'},regeneration_failure:{owner:'asset_generation',domain:'artifacts',diagnosis:'Artifact remains.',severity:'major'}};
    const finding=map[this.scenario],issues:PostRenderIssue[]=finding?[{id:'issue_1',severity:finding.severity,owner:finding.owner,domain:finding.domain,targetType:target.type,targetRef:target.id,evidenceRegions:[{rect:{x:.2,y:.2,width:.2,height:.2},coordinateSpace:'target_normalized',description:'Observed region'}],diagnosis:finding.diagnosis,whyItMatters:'Pixel quality failure.',recommendedAction:'Correct only the affected asset.',confidence:.9}]:[],score=finding?60:this.scenario==='notes'?86:92,verdict:PostRenderVisualReview['verdict']=finding?'regeneration_required':score>=88?'approved':'approved_with_notes';
    return{schemaVersion:POST_RENDER_REVIEW_SCHEMA_VERSION,verdict,overallScore:score,dimensions:{overallQuality:{score,status:'scored',confidence:.9}},issues,strengths:['Coherent output'],confidence:this.scenario==='low_confidence'?.4:.9,assetResults:targets.filter(item=>item.type==='generated_asset').map(item=>({targetRef:item.id,score})),compositeResult:targets.find(item=>item.type==='composite')?{targetRef:targets.find(item=>item.type==='composite')!.id,score}:undefined,requiresRegeneration:issues.some(issue=>issue.owner==='asset_generation'),requiresUpstreamRevision:issues.some(issue=>issue.owner!=='asset_generation')};
  }
}
