import {createHash} from 'node:crypto';
import {buildAssetRegenerationDirectives,buildRegenerationPromptPlan,createUpstreamDirectives,POST_RENDER_REVIEW_SCHEMA_VERSION,resolvePostRenderDecision,type AssetRegenerationDirective,type AssetRegenerationRound,type CompositeRasterizer,type PostRenderReviewSession,type PostRenderVisualQaProvider,type VisualQaTarget} from '../../domain/post-render-review/index.js';
import {canonicalImageJobInput,validateGeneratedImage,type AssetResolutionRecord,type GeneratedAssetStore,type GeneratedImageAsset,type ImageAssetSession,type ImageGenerationProvider,type ImageRegenerationJob} from '../../domain/image-assets/index.js';
import type {ReviewedDesignPackage} from '../../domain/art-director-review/index.js';
import type {ProjectAssetRegistry} from '../../domain/render-engine/index.js';
import {createRenderSession} from '../render-engine/index.js';
import {materializeSvgAssetsForServer} from '../../infrastructure/post-render-review/index.js';
import type {ProjectAIBudgetCoordinator} from '../../infrastructure/ai/index.js';
import type {AIModelCall} from '../../infrastructure/ai/types.js';

const sha=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex');
type CorrectionInput={reviewedDesignPackage:ReviewedDesignPackage;imageAssetSession:ImageAssetSession;assetRegistry:ProjectAssetRegistry};
type CorrectionDependencies={store:GeneratedAssetStore;imageProvider:ImageGenerationProvider;qaProvider:PostRenderVisualQaProvider;rasterizer:CompositeRasterizer;budget:ProjectAIBudgetCoordinator;imageModel:string;regenLimitUsd:number;verificationReserveUsd:number;maxRounds:number;maxMb:number;storageRetries:number};
type PreparedJob={directive:AssetRegenerationDirective;source:GeneratedImageAsset;job:ImageRegenerationJob;estimatedCost:number};

const prepareJobs=(directives:AssetRegenerationDirective[],input:CorrectionInput,d:CorrectionDependencies):PreparedJob[]=>directives.map(directive=>{
  const source=input.imageAssetSession.generatedAssets.find(asset=>asset.id===directive.currentAssetId),original=input.imageAssetSession.jobs.find(job=>job.requirementId===directive.requirementId);
  if(!source||!original)throw new Error(`Regeneration lineage missing for ${directive.requirementId}.`);
  const promptPlan=buildRegenerationPromptPlan(original.promptPlan,directive),fingerprint=sha(canonicalImageJobInput({source:source.checksum,requirement:directive.requirementId,promptPlan,issues:directive.issueIds,corrections:directive.corrections,operation:directive.operation,model:d.imageModel,quality:directive.requestedQuality,size:original.size,policy:POST_RENDER_REVIEW_SCHEMA_VERSION})),job:ImageRegenerationJob={...original,jobId:`regen_${fingerprint.slice(0,16)}`,fingerprint,sourceAssetId:source.id,sourceAssetRefs:[source.backingRef],operation:directive.operation,corrections:directive.corrections,promptPlan,model:d.imageModel,quality:directive.requestedQuality??original.quality};
  return{directive,source,job,estimatedCost:d.imageProvider.estimateCost(job)};
});

export const executeVisualCorrectionLoop=async(initial:PostRenderReviewSession,input:CorrectionInput,d:CorrectionDependencies):Promise<PostRenderReviewSession>=>{
  const review=initial.finalReview;if(!review||resolvePostRenderDecision(review)!=='regeneration_required'||d.maxRounds<1)return{...initial,upstreamDirectives:review?createUpstreamDirectives(review.issues):[]};
  const directives=buildAssetRegenerationDirectives(review,input.imageAssetSession.generatedAssets,input.imageAssetSession.jobs,Boolean(d.imageProvider.edit));
  if(!directives.length)return{...initial,outcome:'upstream_revision_required',upstreamDirectives:[],warnings:[...initial.warnings,'No safe automatic correction mapping.']};
  const prepared=prepareJobs(directives,input,d),estimate=prepared.reduce((sum,item)=>sum+item.estimatedCost,0),snapshot=await d.budget.snapshot(initial.projectId);
  if(estimate+d.verificationReserveUsd>Math.min(snapshot.remainingUsd,snapshot.monthlyRemainingUsd,d.regenLimitUsd))return{...initial,outcome:'failed',warnings:[...initial.warnings,'O limite de geração deste projeto foi atingido antes da correção visual.']};
  const round:AssetRegenerationRound={round:1,sourceRenderSessionId:input.imageAssetSession.renderSession.sessionId,sourceRasterChecksum:initial.qaPlan.compositeTarget?.checksum??'',sourceAssetIds:prepared.map(item=>item.source.id),sourceAssetChecksums:prepared.map(item=>item.source.checksum),issueIds:directives.flatMap(item=>item.issueIds),directives,operationResults:[],newAssetIds:[],newAssetChecksums:[],cost:0,status:'generating'},newAssets:GeneratedImageAsset[]=[];
  for(const item of prepared){
    const operationId=item.job.fingerprint,reservation=await d.budget.reserve({projectId:initial.projectId,stage:'image_regeneration',estimatedCostUsd:item.estimatedCost,stageLimitUsd:d.regenLimitUsd,operationId});let result;
    try{const sourceBytes=await d.store.get(item.source.backingRef,initial.projectId);if(!sourceBytes||sha(sourceBytes)!==item.source.checksum)throw new Error('Source asset backing missing or checksum mismatch.');result=item.job.operation==='edit_if_supported'&&d.imageProvider.edit?await d.imageProvider.edit({job:item.job,sourceBytes,sourceMediaType:item.source.mediaType}):await d.imageProvider.generate(item.job)}catch(error){if(error instanceof Error&&error.message.toLowerCase().includes('timeout')){await d.budget.resolveUnknown(reservation.reservationId);round.operationResults.push({jobId:item.job.jobId,status:'unknown',reason:'provider_timeout_unknown'})}else{await d.budget.release(reservation.reservationId);round.operationResults.push({jobId:item.job.jobId,status:'failed',reason:'provider_rejected'})}continue}
    const actual=result.actualCostUsd??item.estimatedCost,call:AIModelCall={requestId:result.requestId,pass:'image_generation',model:result.model,inputTokens:result.usage?.inputTokens??0,cachedInputTokens:0,cacheWriteTokens:0,outputTokens:result.usage?.outputTokens??0,costUsd:actual,durationMs:result.durationMs,maxOutputTokens:0,outputTokenUtilization:0,repairAttempt:false,stage:'image_regeneration',operationId};await d.budget.commit(reservation.reservationId,call);round.cost+=actual;
    try{validateGeneratedImage(result,d.maxMb)}catch{round.operationResults.push({jobId:item.job.jobId,status:'failed',reason:'generated_output_invalid'});continue}
    const checksum=sha(result.bytes),id=`regenerated_${checksum.slice(0,20)}`;let backingRef:string|undefined;for(let attempt=0;attempt<=d.storageRetries;attempt+=1){try{backingRef=await d.store.put({projectId:initial.projectId,assetId:id,bytes:result.bytes,mediaType:result.mediaType,checksum});break}catch{/* bounded retry */}}
    if(!backingRef){round.operationResults.push({jobId:item.job.jobId,status:'failed',reason:'generated_asset_storage_failed'});continue}
    const asset:GeneratedImageAsset={...item.source,id,backingRef,checksum,fingerprint:item.job.fingerprint,requirementId:item.directive.requirementId,model:result.model,quality:item.job.quality,createdAt:new Date().toISOString(),provenance:[...item.source.provenance,`supersedes:${item.source.id}`]};newAssets.push(asset);round.newAssetIds.push(id);round.newAssetChecksums.push(checksum);round.operationResults.push({jobId:item.job.jobId,status:'succeeded',assetId:id});
  }
  if(newAssets.length!==directives.length){round.status='failed';round.failureReason='mandatory_regeneration_incomplete';return{...initial,regenerationRounds:[round],outcome:'failed',visualApproved:false,cost:initial.cost+round.cost,costBreakdown:{initialQaUsd:initial.cost,escalationUsd:0,regenerationUsd:round.cost,verificationUsd:0,totalUsd:initial.cost+round.cost}}}
  round.status='generated';
  const activeByRequirement=new Map(input.imageAssetSession.generatedAssets.map(asset=>[asset.requirementId,asset]));for(const asset of newAssets)activeByRequirement.set(asset.requirementId,asset);const active=[...activeByRequirement.values()],activeIds=new Set(active.map(asset=>asset.id)),historical=[...input.imageAssetSession.generatedAssets,...newAssets].filter(asset=>!activeIds.has(asset.id)),resolutions:AssetResolutionRecord[]=newAssets.map(asset=>({requirementId:asset.requirementId,assetId:asset.id,supersedesAssetId:input.imageAssetSession.generatedAssets.find(old=>old.requirementId===asset.requirementId)?.id,reason:'post_render_visual_correction',source:'regeneration',createdAt:asset.createdAt}));
  const registry:ProjectAssetRegistry={projectId:initial.projectId,assets:[...input.assetRegistry.assets,...newAssets]},render=createRenderSession({projectId:initial.projectId,reviewedDesignPackage:input.reviewedDesignPackage,assetRegistry:registry,fontAvailability:['Arial','Helvetica','sans-serif']});
  if(render.renderDocument.scenes[0]?.source.layoutId!==input.imageAssetSession.renderSession.renderDocument.scenes[0]?.source.layoutId||render.renderDocument.scenes[0]?.source.routeId!==input.imageAssetSession.renderSession.renderDocument.scenes[0]?.source.routeId||render.artifacts[0]?.width!==input.imageAssetSession.renderSession.artifacts[0]?.width)throw new Error('Regeneration changed protected design invariants.');
  round.resultingRenderSessionId=render.sessionId;round.status='rerendered';const artifact=render.artifacts[0];if(!artifact)throw new Error('Regenerated render artifact missing.');const svg=await materializeSvgAssetsForServer(artifact,registry,d.store),scene=render.renderDocument.scenes[0];if(!scene)throw new Error('Regenerated render scene missing.');const raster=await d.rasterizer.rasterize({svg,width:artifact.width,height:artifact.height,sceneId:scene.sceneId,canonicalSvgChecksum:artifact.checksum,assetChecksums:active.map(asset=>asset.checksum)});round.resultingRasterChecksum=raster.checksum;
  const targets:VisualQaTarget[]=[];for(const asset of newAssets){const bytes=await d.store.get(asset.backingRef,initial.projectId);if(!bytes||sha(bytes)!==asset.checksum){round.status='failed';round.failureReason='corrected_backing_missing_or_mismatch';return{...initial,regenerationRounds:[round],outcome:'failed',visualApproved:false,warnings:[...initial.warnings,'Corrected asset backing could not be verified.']}}targets.push({id:`asset:${asset.id}`,type:'generated_asset',sourceRef:asset.id,width:asset.width,height:asset.height,checksum:asset.checksum,bytes,pixelProvided:true,context:{correction:true,active:true},observability:['correction_verification']});const directive=directives.find(item=>item.requirementId===asset.requirementId);if(directive?.corrections.some(correction=>correction==='improve_product_fidelity'||correction==='fix_face')){const old=input.imageAssetSession.generatedAssets.find(candidate=>candidate.id===directive.currentAssetId),oldBytes=old&&await d.store.get(old.backingRef,initial.projectId);if(old&&oldBytes&&sha(oldBytes)===old.checksum)targets.push({id:`historical:${old.id}`,type:'generated_asset',sourceRef:old.id,width:old.width,height:old.height,checksum:old.checksum,bytes:oldBytes,pixelProvided:true,context:{comparisonRole:'old_identity_reference',active:false},observability:['identity_preservation']})}}
  targets.unshift({id:`composite:${raster.artifactId}`,type:'composite',sourceRef:raster.artifactId,width:raster.width,height:raster.height,checksum:raster.checksum,bytes:raster.bytes,pixelProvided:true,context:{verification:true},observability:['integration']});
  const verified=await d.qaProvider.review(targets,{projectId:initial.projectId,originalIssues:round.issueIds,compactVerification:true}),decision=resolvePostRenderDecision(verified),approved=decision==='approved'||decision==='approved_with_notes';round.verification={issueResults:round.issueIds.map(id=>({issueId:id,resolved:approved})),issuesResolved:approved?round.issueIds:[],issuesRemaining:approved?[]:round.issueIds,newIssues:verified.issues.filter(issue=>!round.issueIds.includes(issue.id)),overallScore:verified.overallScore,approved,confidence:verified.confidence};round.status=approved?'resolved':'failed';
  const priorCost=input.imageAssetSession.cost??{estimatedUsd:0,targetUsd:0,limitUsd:0};
  const updatedSession:ImageAssetSession={...input.imageAssetSession,sessionId:`${input.imageAssetSession.sessionId}_regen_${round.round}`,generatedAssets:[...input.imageAssetSession.generatedAssets,...newAssets],historicalGeneratedAssets:historical,activeGeneratedAssets:active,assetResolutions:[...(input.imageAssetSession.assetResolutions??[]),...resolutions],registry,renderSession:render,visualQaStatus:approved?'passed':'failed',cost:{...priorCost,actualUsd:(priorCost.actualUsd??0)+round.cost+d.verificationReserveUsd}};
  const total=initial.cost+round.cost+d.verificationReserveUsd;return{...initial,regenerationRounds:[round],finalReview:verified,finalRenderSession:render,finalAssetRegistry:registry,outcome:approved?'regenerated_approved':decision==='upstream_revision_required'?'upstream_revision_required':'failed',visualApproved:approved,cost:total,costBreakdown:{initialQaUsd:initial.cost,escalationUsd:0,regenerationUsd:round.cost,verificationUsd:d.verificationReserveUsd,totalUsd:total},upstreamDirectives:createUpstreamDirectives(verified.issues),approvedPackage:approved?{projectId:initial.projectId,reviewSessionId:input.reviewedDesignPackage.reviewSessionId,postRenderReviewSessionId:initial.sessionId,reviewedDesignPackage:input.reviewedDesignPackage,renderSession:render,generatedAssetSession:updatedSession,finalAssets:registry,canonicalArtifacts:render.artifacts,pixelQaSummary:{score:verified.overallScore,verdict:decision},visualApprovalStatus:'approved',provenance:['controlled_asset_regeneration','compact_visual_verification']}:undefined};
};
