import {createHash} from 'node:crypto';
import {buildVisualQaBatches,POST_RENDER_REVIEW_SCHEMA_VERSION,VISUAL_QA_POLICY_VERSION,resolvePostRenderDecision,runLocalPostRenderAudit,validatePostRenderReview,type CompositeRasterizer,type PostRenderReviewSession,type PostRenderVisualQaProvider,type VisualQaTarget} from '../../domain/post-render-review/index.js';
import type {GeneratedAssetStore,ImageAssetSession} from '../../domain/image-assets/index.js';
import type {ReviewedDesignPackage} from '../../domain/art-director-review/index.js';
import type {ProjectAssetRegistry,RenderSession} from '../../domain/render-engine/index.js';
import {materializeSvgAssetsForServer} from '../../infrastructure/post-render-review/index.js';

export interface EnsurePostRenderReviewRequest{projectId:string;reviewedDesignPackage:ReviewedDesignPackage;renderSession:RenderSession;imageAssetSession?:ImageAssetSession;assetRegistry:ProjectAssetRegistry;sourceAssetIds?:string[];existingSession?:PostRenderReviewSession}
type ReviewDependencies={store:GeneratedAssetStore;rasterizer:CompositeRasterizer;provider:PostRenderVisualQaProvider;model:string;estimatedCostUsd:number;maxImages?:number};

export const ensurePostRenderReview=async(r:EnsurePostRenderReviewRequest,d:ReviewDependencies):Promise<PostRenderReviewSession>=>{
  if(r.projectId!==r.renderSession.projectId||r.reviewedDesignPackage.reviewSessionId!==r.renderSession.reviewedDesignPackageRef)throw new Error('Post-render lineage mismatch.');
  const localAudit=await runLocalPostRenderAudit(r.renderSession,r.imageAssetSession,d.store),artifact=r.renderSession.artifacts[0],scene=r.renderSession.renderDocument.scenes[0];
  if(!artifact||!scene)throw new Error('Renderable artifact is missing.');
  const checksums=r.imageAssetSession?.generatedAssets.map(a=>a.checksum)??[],fingerprint=createHash('sha256').update(JSON.stringify({svg:artifact.checksum,assets:checksums,route:scene.source.routeId,layout:scene.source.layoutId,model:d.model,policy:VISUAL_QA_POLICY_VERSION,schema:POST_RENDER_REVIEW_SCHEMA_VERSION})).digest('hex'),sessionId=`qa_${fingerprint.slice(0,20)}`;
  if(r.existingSession?.inputFingerprint===fingerprint)return r.existingSession;
  const emptyPlan={assetTargets:[],batches:[],estimatedCost:0,escalationAllowed:false,reasons:[]};
  if(!localAudit.passed)return{schemaVersion:POST_RENDER_REVIEW_SCHEMA_VERSION,sessionId,projectId:r.projectId,createdAt:new Date().toISOString(),inputFingerprint:fingerprint,localAudit,qaPlan:emptyPlan,regenerationRounds:[],outcome:'failed',visualApproved:false,warnings:localAudit.blockers,cost:0,sourceVersions:{qa:POST_RENDER_REVIEW_SCHEMA_VERSION,policy:VISUAL_QA_POLICY_VERSION}};
  const svg=await materializeSvgAssetsForServer(artifact,r.assetRegistry,d.store),raster=await d.rasterizer.rasterize({svg,width:artifact.width,height:artifact.height,sceneId:scene.sceneId,canonicalSvgChecksum:artifact.checksum,assetChecksums:checksums}),targets:VisualQaTarget[]=[];
  for(const asset of r.imageAssetSession?.generatedAssets??[]){const bytes=await d.store.get(asset.backingRef,r.projectId);if(bytes)targets.push({id:`asset:${asset.id}`,type:'generated_asset',sourceRef:asset.id,width:asset.width,height:asset.height,checksum:asset.checksum,bytes,pixelProvided:true,context:{requirementId:asset.requirementId,quality:asset.quality},observability:['physical_plausibility','content_contamination','ai_artifacts','focal_placement']})}
  targets.push({id:`composite:${raster.artifactId}`,type:'composite',sourceRef:raster.artifactId,width:raster.width,height:raster.height,checksum:raster.checksum,bytes:raster.bytes,pixelProvided:true,context:{format:r.reviewedDesignPackage.layoutPlan.format.id,routeId:scene.source.routeId},observability:['crop','hierarchy','integration','edge_quality']});
  const assetTargets=targets.filter(target=>target.type==='generated_asset'),qaPlan={assetTargets,compositeTarget:targets.find(target=>target.type==='composite'),batches:buildVisualQaBatches(targets,d.maxImages??4).map(batch=>batch.map(target=>target.id)),estimatedCost:assetTargets.length?d.estimatedCostUsd:0,escalationAllowed:true,reasons:assetTargets.length?['generated_pixels_require_review']:['deterministic_composite_only']};
  if(!assetTargets.length)return{schemaVersion:POST_RENDER_REVIEW_SCHEMA_VERSION,sessionId,projectId:r.projectId,createdAt:new Date().toISOString(),inputFingerprint:fingerprint,localAudit,qaPlan,regenerationRounds:[],outcome:'approved',visualApproved:true,warnings:[],cost:0,sourceVersions:{qa:POST_RENDER_REVIEW_SCHEMA_VERSION,policy:VISUAL_QA_POLICY_VERSION},approvedPackage:{projectId:r.projectId,reviewSessionId:r.reviewedDesignPackage.reviewSessionId,postRenderReviewSessionId:sessionId,reviewedDesignPackage:r.reviewedDesignPackage,renderSession:r.renderSession,generatedAssetSession:r.imageAssetSession,finalAssets:r.assetRegistry,canonicalArtifacts:r.renderSession.artifacts,pixelQaSummary:{score:100,verdict:'approved'},visualApprovalStatus:'approved',provenance:['local_pixel_audit']}};
  const review=await d.provider.review(targets,{projectId:r.projectId}),verdict=resolvePostRenderDecision(review);review.verdict=verdict;validatePostRenderReview(review,targets);
  const visualApproved=verdict==='approved'||verdict==='approved_with_notes',outcome=visualApproved?verdict:verdict==='upstream_revision_required'?'upstream_revision_required':'partial';
  return{schemaVersion:POST_RENDER_REVIEW_SCHEMA_VERSION,sessionId,projectId:r.projectId,createdAt:new Date().toISOString(),inputFingerprint:fingerprint,localAudit,qaPlan,initialReview:review,regenerationRounds:[],finalReview:review,finalRenderSession:r.renderSession,outcome,visualApproved,warnings:[],cost:d.estimatedCostUsd,sourceVersions:{qa:POST_RENDER_REVIEW_SCHEMA_VERSION,policy:VISUAL_QA_POLICY_VERSION},approvedPackage:visualApproved?{projectId:r.projectId,reviewSessionId:r.reviewedDesignPackage.reviewSessionId,postRenderReviewSessionId:sessionId,reviewedDesignPackage:r.reviewedDesignPackage,renderSession:r.renderSession,generatedAssetSession:r.imageAssetSession,finalAssets:r.assetRegistry,canonicalArtifacts:r.renderSession.artifacts,pixelQaSummary:{score:review.overallScore,verdict},visualApprovalStatus:'approved',provenance:['post_render_visual_qa']}:undefined};
};
