import type {BrandIntelligenceSession,AdaptedDesignConstraints} from '../brand-intelligence/index.js';import type {ArtDirectionRoute,CreativeDirectionSession} from '../creative-direction/index.js';import type {LayoutIntelligenceSession,LayoutPlan,ResponsiveLayoutFamily} from '../layout-engine/index.js';import type {ReferenceIntelligenceSession} from '../../application/reference-intelligence/index.js';import type {AIUsageResult} from '../../infrastructure/ai/types.js';
export const ART_DIRECTOR_REVIEW_SCHEMA_VERSION='1.0.0' as const;export const CRITIC_POLICY_VERSION='1.0.0' as const;
export type AuditDimension='communicationIntegrity'|'brandIntegrity'|'referenceTransformation'|'creativeConceptIntegrity'|'creativeDeviceIntegrity'|'hierarchy'|'composition'|'typography'|'spacingRhythm'|'negativeSpace'|'alignment'|'grouping'|'visualBalance'|'contentCompleteness'|'safeArea'|'collisionSafety'|'textFit'|'formatSuitability'|'productionFeasibility'|'antiCliche'|'antiAiPlanningDiscipline';
export interface LocalArtDirectorAudit{dimensions:Record<AuditDimension,number>;score:number;blockers:ArtDirectorIssue[];warnings:string[];passed:boolean}
export type Observability='observable_pre_render'|'partially_observable'|'not_observable_until_render';export type RevisionTarget='creative_route'|'layout'|'typography'|'brand_application'|'image_strategy'|'creative_device'|'message_hierarchy'|'format_adaptation'|'none';
export interface ArtDirectorIssue{id:string;severity:'blocker'|'major'|'minor'|'note';domain:string;diagnosis:string;whyItMatters:string;evidenceRefs:string[];recommendedAction:string;revisionTarget:RevisionTarget;confidence:number;observability:Observability}
export type CritiqueDimension='communicationClarity'|'strategicCoherence'|'creativeConceptStrength'|'creativeDevicePurpose'|'brandIntegrity'|'referenceTransformation'|'compositionQuality'|'hierarchyQuality'|'typographicJudgment'|'spatialRhythm'|'negativeSpaceControl'|'visualBalance'|'distinctiveness'|'sophistication'|'antiClicheDiscipline'|'antiAiDiscipline'|'productionFeasibility'|'formatExecution';
export interface SeniorArtDirectorCritique{schemaVersion:typeof ART_DIRECTOR_REVIEW_SCHEMA_VERSION;verdict:'approved'|'approved_with_notes'|'revision_required'|'rejected';overallScore:number;dimensions:Record<CritiqueDimension,number>;strengths:string[];issues:ArtDirectorIssue[];revisionRequired:boolean;recommendedRevisionScope:RevisionScope;confidence:number;observabilityNotes:string[]}
export interface ReviewPacket{projectId:string;brief:unknown;messages:unknown[];route:unknown;routeEvaluation:unknown;brand?:unknown;reference?:unknown;adaptationActions?:unknown[];layout:unknown;localAudit:LocalArtDirectorAudit;untrustedVisualContentPolicy:string}
export interface SeniorArtDirectorCritic{critique(packet:ReviewPacket):Promise<SeniorArtDirectorCritique>}
export type RevisionScope='none'|'layout_only'|'creative_adjustment'|'route_reselection'|'mixed';export interface LayoutRevisionDirective{type:'increase_region'|'decrease_region'|'move_region'|'change_alignment'|'adjust_spacing'|'adjust_type_scale'|'change_grid_allocation'|'increase_negative_space'|'reduce_negative_space'|'resolve_collision'|'protect_safe_area'|'change_layering'|'change_crop_behavior'|'optical_adjustment';targetId:string;intent:string;priority:'required'|'strong'|'preferred'}
export interface CreativeRevisionProposal{sourceRouteId:string;rationale:string;changes:Array<{field:string;reason:string;newValue:unknown}>;preservedDecisions:string[];claimRefsUsed:string[];brandConstraintRefs:string[];referencePrincipleRefs:string[];confidence:number}export interface CreativeRouteRevisionProvider{revise(packet:ReviewPacket,issues:ArtDirectorIssue[]):Promise<CreativeRevisionProposal>}
export interface SeniorArtDirectorVerification{issuesResolved:string[];issuesRemaining:string[];newIssues:ArtDirectorIssue[];approved:boolean;confidence:number}
export interface RevisionRound{round:number;sourceRouteId:string;sourceLayoutId:string;issuesAddressed:string[];scope:RevisionScope;actions:string[];resultingRouteId?:string;resultingLayoutId?:string;localAuditBefore:LocalArtDirectorAudit;localAuditAfter:LocalArtDirectorAudit;verification?:SeniorArtDirectorVerification;status:'resolved'|'partially_resolved'|'failed'}
export interface ReviewQualityProfile{localAuditScore:number;criticScore:number;agreementScore:number;unresolvedRisk:number;confidence:number}
export interface CrossFormatReview{invariantCompliance:number;weakestVariant?:string;consistencyScore:number;variantIssues:ArtDirectorIssue[]}
export interface ArtDirectorReviewRequest{projectId:string;creativeDirection:CreativeDirectionSession;layoutIntelligence:LayoutIntelligenceSession;brandIntelligence?:BrandIntelligenceSession;referenceIntelligence?:ReferenceIntelligenceSession;adaptedDesignConstraints?:AdaptedDesignConstraints;responsiveFamily?:ResponsiveLayoutFamily;format:string;destinationTool:string;existingReviewSession?:ArtDirectorReviewSession}
export interface ReviewedDesignPackage{projectId:string;communicationBrief:CreativeDirectionSession['communicationBrief'];brandIntelligence?:BrandIntelligenceSession;referenceIntelligence?:ReferenceIntelligenceSession;creativeRoute:ArtDirectionRoute;layoutPlan:LayoutPlan;reviewSessionId:string;approvalStatus:'approved'|'approved_with_notes'|'revised_approved';decisionProvenance:string[];sourceVersions:ArtDirectorReviewSession['sourceVersions']}
export interface ArtDirectorReviewSession{schemaVersion:typeof ART_DIRECTOR_REVIEW_SCHEMA_VERSION;sessionId:string;projectId:string;createdAt:string;inputFingerprint:string;originalCreativeDirectionSessionId:string;originalLayoutSessionId:string;localAudit:LocalArtDirectorAudit;critique?:SeniorArtDirectorCritique;revisionRounds:RevisionRound[];finalCreativeRoute?:ArtDirectionRoute;finalLayoutPlan?:LayoutPlan;reviewedDesignPackage?:ReviewedDesignPackage;outcome:'approved'|'approved_with_notes'|'revised_approved'|'partial'|'failed';readyForRender:boolean;quality:ReviewQualityProfile;warnings:string[];aiUsage?:AIUsageResult;cost:number;failureReason?:string;sourceVersions:{creative:string;layout:string;brand?:string;reference?:string;review:string;criticPolicy:string}}
export interface PostRenderVisualReview{review(renderedAsset:unknown):Promise<unknown>}
