import type {VisualApprovedRenderPackage} from '../post-render-review/index.js';
export const EXPORT_SCHEMA_VERSION='1.0.0' as const;export const EXPORT_POLICY_VERSION='1.0.0' as const;
export type ExportFormat='png'|'webp'|'pdf'|'svg'|'zip';
export type ExportProfile='social_png'|'social_webp'|'client_proof_pdf'|'campaign_package'|'meta_ads_package';
export interface ProductionExportRequest{projectId:string;visualApprovedPackage:VisualApprovedRenderPackage;formats:ExportFormat[];profile?:ExportProfile;sceneIds?:string[];includeManifest?:boolean;includePdf?:boolean;includeZip?:boolean;existingSession?:ProductionExportSession;projectSlug?:string}
export interface ProductionExportArtifact{artifactId:string;projectId:string;sceneId?:string;format:ExportFormat;filename:string;mediaType:string;width?:number;height?:number;checksum:string;byteSize:number;backingRef?:string;source:{visualApprovedPackageFingerprint:string;renderSessionId:string;canonicalArtifactChecksum:string};status:'ready'|'failed';warnings:string[];createdAt:string;lastAccessedAt?:string;retentionClass:'standard'}
export interface ProductionManifest{schemaVersion:typeof EXPORT_SCHEMA_VERSION;projectId:string;packageFingerprint:string;exportedFormats:ExportFormat[];scenes:Array<{filename:string;format:ExportFormat;width?:number;height?:number;checksum:string;byteSize:number;formatId?:string;placement:string;sceneId?:string;qaStatus:'approved'}>;provenance:{reviewSessionId:string;postRenderReviewSessionId:string;renderSessionId:string;versions:Record<string,string|undefined>};pixelQaScore:number;visualApprovalStatus:'approved'}
export interface ProductionExportSession{schemaVersion:typeof EXPORT_SCHEMA_VERSION;sessionId:string;projectId:string;createdAt:string;inputFingerprint:string;profile:ExportProfile;artifacts:ProductionExportArtifact[];manifest?:ProductionManifest;packageArtifact?:ProductionExportArtifact;status:'ready'|'partial'|'failed';warnings:string[];cost:{aiUsd:0};sourceVersions:Record<string,string|undefined>;cacheHit:boolean;storageKind:'memory'|'durable'|'unavailable'}
export interface ProductionPreflightResult{passed:boolean;blockers:string[];warnings:string[];activeAssetCount:number;historicalAssetsIgnored:number;sceneCount:number}
export interface ProductionArtifactReadHandle{url:string;expiresAt:string;mediaType:string;filename:string}
export interface ProductionArtifactStore{readonly kind:'memory'|'durable'|'unavailable';put(input:{projectId:string;exportFingerprint:string;artifactId:string;filename:string;bytes:Uint8Array;mediaType:string;checksum:string}):Promise<string>;get(ref:string,projectId:string):Promise<Uint8Array|undefined>;exists(ref:string,projectId:string):Promise<boolean>;createReadHandle?(ref:string,projectId:string,mediaType:string,filename:string,ttlSeconds:number):Promise<ProductionArtifactReadHandle>;health():Promise<{status:'ok'|'degraded';store:'memory'|'durable'|'unavailable';private:boolean;signedReads:boolean}>}
export interface RasterEncoder{encodePng(svg:string,width:number,height:number):Promise<Uint8Array>;encodeWebp(png:Uint8Array,quality:number):Promise<Uint8Array>;inspect(bytes:Uint8Array):Promise<{format:string;width:number;height:number}>}
export interface SelfContainedSvgExporter{export(svg:string,resolve:(assetId:string)=>Promise<{bytes:Uint8Array;mediaType:string}>):Promise<{bytes:Uint8Array;warnings:string[]}>}
export interface ApprovedProductionVariant{variantId:string;formatId:string;width:number;height:number;visualApprovedPackage:VisualApprovedRenderPackage}
export interface ApprovedProductionFamily{familyId:string;campaignId:string;variants:ApprovedProductionVariant[];invariants:{creativeConcept?:string;campaignIdentity?:string;messageHierarchy?:string;brand?:string;heroRole?:string}}
export interface ProductionFamilyValidation{valid:boolean;metaAdsPackageReady:boolean;missingVariants:string[];rejectedVariants:string[]}
