CREATE TABLE IF NOT EXISTS projects (project_id text PRIMARY KEY, schema_version text NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, status text NOT NULL, revision integer NOT NULL DEFAULT 1, active_version_id text, latest_production_authority_id text);
CREATE TABLE IF NOT EXISTS project_versions (version_id text NOT NULL, project_id text NOT NULL REFERENCES projects(project_id), revision integer NOT NULL, created_at timestamptz NOT NULL, status text NOT NULL, PRIMARY KEY(project_id, version_id));
CREATE INDEX IF NOT EXISTS project_versions_active_idx ON project_versions(project_id, revision DESC);
CREATE TABLE IF NOT EXISTS workflow_checkpoints (checkpoint_id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(project_id), version_id text NOT NULL, stage text NOT NULL, operation_id text NOT NULL, fingerprint text NOT NULL, revision integer NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL, UNIQUE(project_id, operation_id), UNIQUE(project_id, stage, fingerprint));
CREATE INDEX IF NOT EXISTS workflow_project_stage_idx ON workflow_checkpoints(project_id, stage, revision DESC);
CREATE TABLE IF NOT EXISTS production_authorities (authority_id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(project_id), version_id text NOT NULL, operation_id text NOT NULL, fingerprint text NOT NULL, post_render_review_session_id text NOT NULL, render_session_id text NOT NULL, status text NOT NULL, visual_approved_package jsonb NOT NULL, post_render_review jsonb NOT NULL, active_asset_resolutions jsonb NOT NULL, created_at timestamptz NOT NULL, UNIQUE(project_id, operation_id), UNIQUE(project_id, fingerprint));
CREATE INDEX IF NOT EXISTS authority_project_idx ON production_authorities(project_id, created_at DESC);
CREATE TABLE IF NOT EXISTS production_export_sessions (export_session_id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(project_id), authority_id text NOT NULL REFERENCES production_authorities(authority_id), operation_id text NOT NULL, input_fingerprint text NOT NULL, profile text NOT NULL, status text NOT NULL, session_metadata jsonb NOT NULL, created_at timestamptz NOT NULL, UNIQUE(project_id, operation_id), UNIQUE(project_id, authority_id, input_fingerprint));
CREATE INDEX IF NOT EXISTS exports_project_idx ON production_export_sessions(project_id, created_at DESC);
