ALTER TABLE projects ADD COLUMN IF NOT EXISTS latest_campaign_family_authority_id text;
CREATE TABLE IF NOT EXISTS campaign_variant_families(family_id text PRIMARY KEY,project_id text NOT NULL REFERENCES projects(project_id),operation_id text NOT NULL,input_fingerprint text NOT NULL,family_definition_id text NOT NULL,primary_format_id text NOT NULL,status text NOT NULL,invariants jsonb NOT NULL,family_snapshot jsonb NOT NULL,revision integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,UNIQUE(project_id,operation_id));
CREATE TABLE IF NOT EXISTS campaign_variants(variant_id text PRIMARY KEY,family_id text NOT NULL REFERENCES campaign_variant_families(family_id),project_id text NOT NULL REFERENCES projects(project_id),format_id text NOT NULL,width integer NOT NULL,height integer NOT NULL,status text NOT NULL,input_fingerprint text NOT NULL,layout_session_id text,review_session_id text,render_session_id text,image_asset_session_id text,post_render_review_session_id text,production_authority_id text,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,UNIQUE(family_id,format_id));
CREATE TABLE IF NOT EXISTS campaign_family_authorities(family_authority_id text PRIMARY KEY,family_id text NOT NULL REFERENCES campaign_variant_families(family_id),project_id text NOT NULL REFERENCES projects(project_id),operation_id text NOT NULL,fingerprint text NOT NULL,variant_authority_ids jsonb NOT NULL,status text NOT NULL,authority_snapshot jsonb NOT NULL,created_at timestamptz NOT NULL,UNIQUE(project_id,operation_id));
CREATE TABLE IF NOT EXISTS campaign_family_export_sessions(export_session_id text PRIMARY KEY,family_authority_id text NOT NULL REFERENCES campaign_family_authorities(family_authority_id),family_id text NOT NULL REFERENCES campaign_variant_families(family_id),project_id text NOT NULL REFERENCES projects(project_id),operation_id text NOT NULL,input_fingerprint text NOT NULL,status text NOT NULL,artifact_metadata jsonb NOT NULL,created_at timestamptz NOT NULL,UNIQUE(project_id,operation_id));
CREATE INDEX IF NOT EXISTS campaign_families_project_updated_idx ON campaign_variant_families(project_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS campaign_variants_family_idx ON campaign_variants(family_id);
ALTER TABLE projects DROP CONSTRAINT IF EXISTS projects_latest_campaign_family_authority_fk;
ALTER TABLE projects ADD CONSTRAINT projects_latest_campaign_family_authority_fk FOREIGN KEY(latest_campaign_family_authority_id) REFERENCES campaign_family_authorities(family_authority_id) DEFERRABLE INITIALLY DEFERRED;
