import type {ImageAssetSession} from '../image-assets/index.js';import type {ReviewedDesignPackage} from '../art-director-review/index.js';import type {ProjectAssetRegistry,RenderSession,RenderedSvgArtifact} from '../render-engine/index.js';
export const POST_RENDER_REVIEW_SCHEMA_VERSION='1.0.0' as const;export const VISUAL_QA_POLICY_VERSION='1.0.0' as const;
export type VisualIssueOwner='asset_generation'|'render_composition'|'layout'|'typography'|'brand_asset'|'creative_direction'|'unknown';export type PostRenderVerdict='approved'|'approved_with_notes'|'regeneration_required'|'upstream_revision_required'|'rejected';export type QaDimensionStatus={score:number|null;status:'scored'|'not_applicable';confidence:number};
export interface PixelEvidenceRegion{rect:{x:number;y:number;width:number;height:number};coordinateSpace:'target_normalized';description:string}
export interface PostRenderIssue{id:string;severity:'blocker'|'major'|'minor'|'note';owner:VisualIssueOwner;domain:string;targetType:'generated_asset'|'composite';targetRef:string;evidenceRegions:PixelEvidenceRegion[];diagnosis:string;whyItMatters:string;recommendedAction:string;confidence:number}
export interface VisualQaTarget{id:string;type:'generated_asset'|'composite';sourceRef:string;width:number;height:number;checksum:string;bytes:Uint8Array;context:Record<string,unknown>;observability:string[]}
export interface PostRenderVisualReview{schemaVersion:typeof POST_RENDER_REVIEW_SCHEMA_VERSION;verdict:PostRenderVerdict;overallScore:number;dimensions:Record<string,QaDimensionStatus>;issues:PostRenderIssue[];strengths:string[];confidence:number;assetResults:Array<{targetRef:string;score:number}>;compositeResult?:{targetRef:string;score:number};requiresRegeneration:boolean;requiresUpstreamRevision:boolean}
export interface LocalPostRenderAudit{passed:boolean;blockers:string[];checks:Record<string,boolean>}
export interface RasterizedCompositeArtifact{artifactId:string;sceneId:string;width:number;height:number;mediaType:'image/png';bytes:Uint8Array;checksum:string;canonicalSvgChecksum:string;generatedAssetChecksums:string[];ephemeral:true}
export interface CompositeRasterizer{rasterize(input:{svg:string;width:number;height:number;sceneId:string;canonicalSvgChecksum:string;assetChecksums:string[]}):Promise<RasterizedCompositeArtifact>}
export interface PostRenderVisualQaProvider{readonly id:string;review(targets:VisualQaTarget[],context:Record<string,unknown>):Promise<PostRenderVisualReview>}
export interface VisualQaPlan{assetTargets:VisualQaTarget[];compositeTarget?:VisualQaTarget;batches:string[][];estimatedCost:number;escalationAllowed:boolean;reasons:string[]}
export interface UpstreamRepairDirective{owner:Exclude<VisualIssueOwner,'asset_generation'|'unknown'>;issueIds:string[];targetStage:'renderer'|'layout'|'typography'|'brand'|'creative_direction';diagnosis:string;requiredChange:string}
export interface ControlledAssetRegenerationPlan{assetIds:string[];issueIds:string[];directives:string[];mode:'edit_if_supported'|'replace';estimatedCostUsd:number;allowed:boolean;reason?:string}
export interface VisualApprovedRenderPackage{projectId:string;reviewSessionId:string;postRenderReviewSessionId:string;reviewedDesignPackage:ReviewedDesignPackage;renderSession:RenderSession;generatedAssetSession?:ImageAssetSession;finalAssets:ProjectAssetRegistry;canonicalArtifacts:RenderedSvgArtifact[];pixelQaSummary:{score:number;verdict:PostRenderVerdict};visualApprovalStatus:'approved';provenance:string[]}
export interface PostRenderReviewSession{schemaVersion:typeof POST_RENDER_REVIEW_SCHEMA_VERSION;sessionId:string;projectId:string;createdAt:string;inputFingerprint:string;localAudit:LocalPostRenderAudit;qaPlan:VisualQaPlan;initialReview?:PostRenderVisualReview;regenerationRounds:unknown[];finalReview?:PostRenderVisualReview;finalRenderSession?:RenderSession;outcome:'approved'|'approved_with_notes'|'regenerated_approved'|'upstream_revision_required'|'partial'|'failed';visualApproved:boolean;warnings:string[];cost:number;sourceVersions:Record<string,string|undefined>;approvedPackage?:VisualApprovedRenderPackage}
