import {CREATIVE_DIRECTION_SCHEMA_VERSION,buildCommunicationBrief,buildMessageHierarchy,buildStrategicFrame,evaluateGovernedCreativeRoute,evaluateRouteDiversity,normalizeCreativeCopy,selectBestCreativeRoute,validateCreativeDirectionSession,type CreativeDirectionQuality,type CreativeDirectionRequest,type CreativeDirectionSession,type CreativeRouteEvaluation} from '../../domain/creative-direction/index.js';
import {BudgetedAIExecutor} from '../../infrastructure/ai/budget/executor.js';
import {createLedger,type BudgetStore} from '../../infrastructure/ai/budget/budget-tracker.js';
import {AISchemaError} from '../../infrastructure/ai/providers/errors.js';
import type {OpenAIConfig} from '../../infrastructure/ai/providers/openai/config.js';
import type {AIProvider} from '../../infrastructure/ai/types.js';
import {OpenAICreativeRouteGenerator} from './openai-generator.js';
import {adaptReferenceDNA,resolveBrandReferenceCompatibility} from '../../domain/brand-intelligence/index.js';
export const AI_CREATIVE_DIRECTION_TARGET_USD=.12,AI_CREATIVE_DIRECTION_MAX_USD=.18;
const cache=new Map<string,CreativeDirectionSession>();
const normalize=(value:unknown):unknown=>Array.isArray(value)?value.map(normalize):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).filter(([key])=>!['forensics','aiUsage','existingSession'].includes(key)).sort().map(([key,item])=>[key,normalize(item)])):value;
export const fingerprintCreativeDirection=async(request:CreativeDirectionRequest)=>{const payload=JSON.stringify(normalize({...request,copy:normalizeCreativeCopy(request.copy),creativeSchema:CREATIVE_DIRECTION_SCHEMA_VERSION,referenceVersion:request.referenceIntelligence?.sessionId,brandVersion:request.brandIntelligence?.sessionId}));const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(payload));return[...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('');};
const quality=(evaluations:CreativeRouteEvaluation[],diversity:number):CreativeDirectionQuality=>{const eligible=evaluations.filter(item=>item.eligible),average=(key:keyof CreativeRouteEvaluation)=>eligible.length?eligible.reduce((sum,item)=>sum+Number(item[key]),0)/eligible.length:0,result={strategicCoherence:average('communicationFit'),routeDiversity:diversity,brandIntegrity:1-average('routeBrandDriftRisk'),referenceTransformation:average('referenceTransformation'),creativeDistinctiveness:average('distinctiveness'),constraintCompliance:average('constraintCompliance'),overall:0};result.overall=(result.strategicCoherence+result.routeDiversity+result.brandIntegrity+result.referenceTransformation+result.creativeDistinctiveness+result.constraintCompliance)/6;return result;};
const usage=(ledger:ReturnType<typeof createLedger>,config:OpenAIConfig)=>({inputTokens:ledger.inputTokens,cachedInputTokens:ledger.cachedInputTokens,cacheWriteTokens:ledger.cacheWriteTokens,outputTokens:ledger.outputTokens,totalCostUsd:ledger.totalCostUsd,targetCostUsd:config.targetProjectCostUsd,limitCostUsd:config.maxProjectCostUsd,modelsUsed:[...new Set(ledger.modelCalls.map(call=>call.model))],calls:ledger.modelCalls,escalationStatus:'not_needed' as const});
export const createCreativeDirection=async(request:CreativeDirectionRequest,deps:{provider:AIProvider;budgetStore:BudgetStore;config:OpenAIConfig}):Promise<CreativeDirectionSession>=>{
  const brand=request.brandIntelligence?.brandDNA,compatibility=brand?resolveBrandReferenceCompatibility(brand,request.referenceIntelligence?.designDNA):undefined,effectiveAdapted=request.adaptedDesignConstraints??(brand?adaptReferenceDNA(request.referenceIntelligence?.designDNA,brand,compatibility):undefined),effectiveRequest={...request,adaptedDesignConstraints:effectiveAdapted};
  const inputFingerprint=await fingerprintCreativeDirection(effectiveRequest);if(request.existingSession?.inputFingerprint===inputFingerprint&&validateCreativeDirectionSession(request.existingSession))return request.existingSession;const cached=cache.get(inputFingerprint);if(cached)return cached;
  const brief=buildCommunicationBrief(effectiveRequest),frame=buildStrategicFrame(brief,effectiveRequest),messageHierarchy=buildMessageHierarchy(brief),initialLedger=await deps.budgetStore.getProject(request.projectId)??createLedger(request.projectId);const executor=new BudgetedAIExecutor(deps.provider,deps.budgetStore,deps.config.maxProjectCostUsd,initialLedger,Number.POSITIVE_INFINITY,{monthlyLimitUsd:deps.config.monthlyBudgetUsd,safetyFactor:deps.config.budgetReservationSafetyFactor,ttlSeconds:deps.config.budgetReservationTtlSeconds,stage:'creative_direction',stageLimitUsd:AI_CREATIVE_DIRECTION_MAX_USD});
  try{
    const candidates=await new OpenAICreativeRouteGenerator(executor,deps.config.forensicsModel).generate({brief,request:effectiveRequest}),diversity=evaluateRouteDiversity(candidates.routes),context={brief,messageHierarchy,brandIntelligence:request.brandIntelligence,adaptedDesignConstraints:effectiveAdapted,referenceIntelligence:request.referenceIntelligence,format:request.format},evaluations=candidates.routes.map(route=>evaluateGovernedCreativeRoute(route,context,diversity.minimum)),selected=diversity.sufficient?selectBestCreativeRoute(candidates.routes,evaluations):undefined,finalLedger=executor.getLedger(),status=selected?.route?'ready' as const:'failed' as const;
    const session:CreativeDirectionSession={schemaVersion:CREATIVE_DIRECTION_SCHEMA_VERSION,sessionId:crypto.randomUUID(),projectId:request.projectId,createdAt:new Date().toISOString(),inputFingerprint,communicationBrief:brief,strategicFrame:candidates.strategicFrame??frame,routes:candidates.routes,evaluations,selectedRouteId:selected?.route?.id,selectedRoute:selected?.route,status,...(status==='failed'?{failureReason:diversity.sufficient?'no_eligible_route' as const:'insufficient_divergence' as const}:{}),quality:quality(evaluations,diversity.minimum),warnings:[...(!request.brandIntelligence||request.brandIntelligence.identityMode==='none'?['Brand protection unavailable.']:[]),...(!request.referenceIntelligence?['Reference structural guidance unavailable.']:[])],aiUsage:usage(finalLedger,deps.config),cost:finalLedger.totalCostUsd-initialLedger.totalCostUsd,sourceVersions:{referenceSession:request.referenceIntelligence?.sessionId,brandSession:request.brandIntelligence?.sessionId,creativeSchema:CREATIVE_DIRECTION_SCHEMA_VERSION}};cache.set(inputFingerprint,session);return session;
  }catch(error){if(!(error instanceof AISchemaError))throw error;const finalLedger=executor.getLedger();return{schemaVersion:CREATIVE_DIRECTION_SCHEMA_VERSION,sessionId:crypto.randomUUID(),projectId:request.projectId,createdAt:new Date().toISOString(),inputFingerprint,communicationBrief:brief,strategicFrame:frame,routes:[],evaluations:[],status:'failed',failureReason:'generation_failed',quality:quality([],0),warnings:['Creative route generation failed structural validation.'],aiUsage:usage(finalLedger,deps.config),cost:finalLedger.totalCostUsd-initialLedger.totalCostUsd,sourceVersions:{referenceSession:request.referenceIntelligence?.sessionId,brandSession:request.brandIntelligence?.sessionId,creativeSchema:CREATIVE_DIRECTION_SCHEMA_VERSION}};}
};
