const score = {type: 'number', minimum: 0, maximum: 1} as const;
const strings = {type: 'array', items: {type: 'string'}} as const;
const message = {type: 'object', additionalProperties: false, properties: {role: {type: 'string', enum: ['hook','headline','subheadline','benefit','offer','proof','data','cta','legal','support']}, contentReference: {type: 'string'}, priority: {type: 'number'}, visualImportance: score, confidence: score}, required: ['role','contentReference','priority','visualImportance','confidence']} as const;
const frame = {type: 'object', additionalProperties: false, properties: {communicationProblem:{type:'string'},communicationOpportunity:{type:'string'},singleMindedProposition:{type:'string'},desiredResponse:{type:'string'},messageHierarchy:{type:'array',items:message},brandRole:{type:'string'},referenceRole:{type:'string'},formatRole:{type:'string'},creativeOpportunity:{type:'string'},confidence:score},required:['communicationProblem','communicationOpportunity','singleMindedProposition','desiredResponse','messageHierarchy','brandRole','referenceRole','formatRole','creativeOpportunity','confidence']} as const;
const vectorKeys = ['abstraction','humanFocus','productFocus','editoriality','dynamism','minimalism','dimensionality','narrativeDepth','typographicExpression'];
const vector = {type:'object',additionalProperties:false,properties:Object.fromEntries(vectorKeys.map((key)=>[key,score])),required:vectorKeys} as const;
const tension = {type:'object',additionalProperties:false,properties:{poleA:{type:'string'},poleB:{type:'string'},resolution:{type:'string'},relevance:{type:'string'},confidence:score},required:['poleA','poleB','resolution','relevance','confidence']} as const;
const metaphor = {type:'object',additionalProperties:false,properties:{concept:{type:'string'},literalness:score,relevance:score,originality:score,executionRisk:score,confidence:score},required:['concept','literalness','relevance','originality','executionRisk','confidence']} as const;
const route = {type:'object',additionalProperties:false,properties:{
  id:{type:'string'},internalName:{type:'string'},territory:{type:'object',additionalProperties:false,properties:{name:{type:'string'},logic:{type:'string'},relevance:{type:'string'},confidence:score},required:['name','logic','relevance','confidence']},
  concept:{type:'object',additionalProperties:false,properties:{name:{type:'string'},coreIdea:{type:'string'},strategicRationale:{type:'string'},visualThesis:{type:'object',additionalProperties:false,properties:{dominantElement:{type:'string'},dominanceReason:{type:'string'},memorabilityMechanism:{type:'string'},communicatingRelationship:{type:'string'},brandRecognition:{type:'string'}},required:['dominantElement','dominanceReason','memorabilityMechanism','communicatingRelationship','brandRecognition']},audienceTakeaway:{type:'string'},brandRelevance:{type:'string'},communicationRelevance:{type:'string'}},required:['name','coreIdea','strategicRationale','visualThesis','audienceTakeaway','brandRelevance','communicationRelevance']},strategicRationale:{type:'string'},creativeTension:{anyOf:[tension,{type:'null'}]},visualMetaphor:{anyOf:[metaphor,{type:'null'}]},
  creativeDevice:{type:'object',additionalProperties:false,properties:{name:{type:'string'},description:{type:'string'},communicationFunction:{type:'string'},brandConnection:{type:'string'},repeatability:score,distinctiveness:score,productionFeasibility:score},required:['name','description','communicationFunction','brandConnection','repeatability','distinctiveness','productionFeasibility']},heroStrategy:{type:'string',enum:['product','human','typography','data','symbolic_object','graphic_device','mixed','none']},compositionStrategy:{type:'string'},hierarchyStrategy:{type:'string'},typographyBehavior:{type:'object',additionalProperties:false,properties:{typographicRole:{type:'string'},scaleContrast:{type:'string'},density:{type:'string'},expressiveness:{type:'string'},alignmentCharacter:{type:'string'},headlineBehavior:{type:'string'},dataBehavior:{type:'string'}},required:['typographicRole','scaleContrast','density','expressiveness','alignmentCharacter','headlineBehavior','dataBehavior']},colorBehavior:{type:'object',additionalProperties:false,properties:{dominance:{type:'string'},accentBehavior:{type:'string'},contrast:{type:'string'},coverageLogic:{type:'string'},backgroundRole:{type:'string'},foregroundRole:{type:'string'},tokenPolicy:{type:'string'}},required:['dominance','accentBehavior','contrast','coverageLogic','backgroundRole','foregroundRole','tokenPolicy']},
  imageStrategy:{type:'object',additionalProperties:false,properties:{mode:{type:'string',enum:['photography','illustration','3d','abstract','mixed','none']},subjectRole:{type:'string'},framingCharacter:{type:'string'},lightingCharacter:{type:'string'},backgroundCharacter:{type:'string'},authenticity:{type:'string'},depthCharacter:{type:'string'},retouchingCharacter:{type:'string'}},required:['mode','subjectRole','framingCharacter','lightingCharacter','backgroundCharacter','authenticity','depthCharacter','retouchingCharacter']},shapeStrategy:{type:'string'},materialStrategy:{type:'object',additionalProperties:false,properties:{required:{type:'boolean'},characters:strings,conceptualRole:{type:'string'}},required:['required','characters','conceptualRole']},textureStrategy:{type:'string'},spatialStrategy:{type:'object',additionalProperties:false,properties:{density:{type:'string'},negativeSpaceRole:{type:'string'},visualBreathing:{type:'string'},layering:{type:'string'},compression:{type:'string'},expansion:{type:'string'},rhythm:{type:'string'}},required:['density','negativeSpaceRole','visualBreathing','layering','compression','expansion','rhythm']},graphicDeviceStrategy:{type:'string'},narrativeBehavior:{type:'string'},copyHierarchy:{type:'array',items:message},brandExpression:{type:'string'},referencePrinciplesUsed:strings,adaptationActionsUsed:strings,distinctiveAssetsUsed:strings,antiClicheStrategy:strings,antiAiStrategy:strings,
  formatAdaptability:{type:'object',additionalProperties:false,properties:{score, strengths:strings,risks:strings,adaptationNotes:strings},required:['score','strengths','risks','adaptationNotes']},productionFeasibility:score,divergenceVector:vector,confidence:score,provenance:{type:'array',items:{type:'object',additionalProperties:false,properties:{decision:{type:'string'},source:{type:'string',enum:['communication_strategy','reference_structure','brand_hard_constraint','brand_soft_preference','brand_distinctive_asset','adaptation','creative_concept','creative_device','format','execution_interpretation']},confidence:{anyOf:[score,{type:'null'}]}},required:['decision','source','confidence']}},declaredHardViolations:strings,inventedClaims:strings,literalReferenceTraits:strings,declaredBrandDriftTraits:strings
},required:['id','internalName','territory','concept','strategicRationale','creativeTension','visualMetaphor','creativeDevice','heroStrategy','compositionStrategy','hierarchyStrategy','typographyBehavior','colorBehavior','imageStrategy','shapeStrategy','materialStrategy','textureStrategy','spatialStrategy','graphicDeviceStrategy','narrativeBehavior','copyHierarchy','brandExpression','referencePrinciplesUsed','adaptationActionsUsed','distinctiveAssetsUsed','antiClicheStrategy','antiAiStrategy','formatAdaptability','productionFeasibility','divergenceVector','confidence','provenance','declaredHardViolations','inventedClaims','literalReferenceTraits','declaredBrandDriftTraits']} as const;
export const CREATIVE_DIRECTION_OUTPUT_SCHEMA = {type:'object',additionalProperties:false,properties:{strategicFrame:frame,routes:{type:'array',minItems:3,maxItems:3,items:route}},required:['strategicFrame','routes']} as const;
