import {Router} from 'express';
import {createProductionExport} from '../../application/export-engine/index.js';
import type {ProductionExportRequest} from '../../domain/export-engine/index.js';
import {applicationGeneratedAssetStore} from '../../infrastructure/image-generation/index.js';
import {applicationProductionArtifactStore,loadExportConfig,NodeProductionRasterEncoder,SafeSelfContainedSvgExporter} from '../../infrastructure/export-engine/index.js';
import {getExportSession,saveExportSession} from '../export-session-store.js';
import {resolveVisualApprovedPackage} from '../production-authority-store.js';

export const createExportsRouter=()=>{
  const router=Router(),config=loadExportConfig();
  router.post('/create',async(req,res)=>{try{
    const body=req.body as Partial<ProductionExportRequest>&{postRenderReviewSessionId?:string};
    if(!body.projectId||!body.postRenderReviewSessionId||!Array.isArray(body.formats))return res.status(400).json({error:'Approved production lineage and formats are required.'});
    const authority=resolveVisualApprovedPackage(body.projectId,body.postRenderReviewSessionId)??body.visualApprovedPackage;if(!authority||authority.postRenderReviewSessionId!==body.postRenderReviewSessionId)return res.status(403).json({error:'Approved production authority was not found.'});
    const request={...body,projectId:body.projectId,visualApprovedPackage:authority,formats:body.formats} as ProductionExportRequest,result=await createProductionExport(request,{assetStore:applicationGeneratedAssetStore,artifactStore:applicationProductionArtifactStore,rasterEncoder:new NodeProductionRasterEncoder(),svgExporter:new SafeSelfContainedSvgExporter(),maxSingleFileMb:config.maxSingleFileMb,maxPackageMb:config.maxPackageMb});saveExportSession(result);
    const debug=req.query.debug==='export'?{preflight:'passed',sourcePackage:result.inputFingerprint,sceneCount:result.manifest?.scenes.length??result.artifacts.filter(artifact=>artifact.sceneId).length,requestedFormats:request.formats,artifacts:result.artifacts.map(artifact=>({id:artifact.artifactId,format:artifact.format,dimensions:[artifact.width,artifact.height],checksum:artifact.checksum})),activeAssetCount:authority.generatedAssetSession?.activeGeneratedAssets?.length??0,historicalAssetsIgnored:authority.generatedAssetSession?.historicalGeneratedAssets?.length??0,cacheHit:result.cacheHit,packageStatus:result.status,storageKind:result.storageKind}:undefined;return res.json(debug?{...result,debugExport:debug}:result);
  }catch(error){return res.status(422).json({error:error instanceof Error?error.message:'Export failed.'})}});
  router.post('/read-handle',async(req,res)=>{try{const {projectId,exportSessionId,artifactId}=req.body??{},session=getExportSession(String(exportSessionId));if(!session||session.projectId!==projectId)return res.status(403).json({error:'Export lineage is invalid.'});const artifact=session.artifacts.find(item=>item.artifactId===artifactId);if(!artifact?.backingRef||!await applicationProductionArtifactStore.exists(artifact.backingRef,projectId))return res.status(404).json({error:'Export artifact unavailable.'});if(applicationProductionArtifactStore.kind==='memory')return res.json({url:`/api/exports/download?projectId=${encodeURIComponent(projectId)}&exportSessionId=${encodeURIComponent(exportSessionId)}&artifactId=${encodeURIComponent(artifactId)}`,expiresAt:new Date(Date.now()+config.readHandleTtlSeconds*1000).toISOString(),mediaType:artifact.mediaType,filename:artifact.filename});if(!applicationProductionArtifactStore.createReadHandle)return res.status(503).json({error:'Private downloads unavailable.'});return res.json(await applicationProductionArtifactStore.createReadHandle(artifact.backingRef,projectId,artifact.mediaType,artifact.filename,config.readHandleTtlSeconds))}catch{return res.status(404).json({error:'Export artifact unavailable.'})}});
  router.get('/download',async(req,res)=>{try{const projectId=String(req.query.projectId??''),session=getExportSession(String(req.query.exportSessionId??''));if(!session||session.projectId!==projectId)return res.status(403).end();const artifact=session.artifacts.find(item=>item.artifactId===String(req.query.artifactId??''));if(!artifact?.backingRef)return res.status(404).end();const bytes=await applicationProductionArtifactStore.get(artifact.backingRef,projectId);if(!bytes)return res.status(404).end();res.setHeader('Content-Type',artifact.mediaType);res.setHeader('Content-Disposition',`attachment; filename="${artifact.filename.replace(/["\\\r\n]/g,'-')}"`);return res.send(Buffer.from(bytes))}catch{return res.status(404).end()}});
  return router;
};
