import {Router} from 'express';
import {ensurePostRenderReview,executeVisualCorrectionLoop,type EnsurePostRenderReviewRequest} from '../../application/post-render-review/index.js';
import {OpenAIProvider,ProjectAIBudgetCoordinator,applicationBudgetStore,createOpenAIClient,loadOpenAIConfig} from '../../infrastructure/ai/index.js';
import {MockImageGenerationProvider,OpenAIImageGenerationProvider,applicationGeneratedAssetStore} from '../../infrastructure/image-generation/index.js';
import {BudgetedPostRenderVisualQaProvider,MockPostRenderVisualQaProvider,OpenAIPostRenderVisualQaProvider,ResvgCompositeRasterizer} from '../../infrastructure/post-render-review/index.js';
import {registerVisualApprovedPackage} from '../production-authority-store.js';

export const createVisualQaRouter=()=>{
  const router=Router();
  router.post('/review',async(req,res)=>{try{
    if('prompt'in(req.body??{}))return res.status(400).json({error:'Arbitrary QA prompts are not accepted.'});
    const body=req.body as EnsurePostRenderReviewRequest,config=loadOpenAIConfig(),mock=(process.env.AI_VISUAL_QA_PROVIDER??'openai')==='mock',model=config.postRenderQaModel;
    const raw=mock?new MockPostRenderVisualQaProvider((process.env.AI_VISUAL_QA_MOCK_SCENARIO??'approved') as never):new OpenAIPostRenderVisualQaProvider(new OpenAIProvider(config),model,config.postRenderQaMaxImages),coordinator=new ProjectAIBudgetCoordinator(applicationBudgetStore,{projectLimitUsd:config.maxProjectCostUsd,monthlyLimitUsd:config.monthlyBudgetUsd,safetyFactor:config.budgetReservationSafetyFactor,ttlSeconds:config.budgetReservationTtlSeconds}),provider=new BudgetedPostRenderVisualQaProvider(raw,coordinator,String(body.projectId),model,config.postRenderQaTargetUsd,config.postRenderQaMaxUsd,config.postRenderQaMaxImages),rasterizer=new ResvgCompositeRasterizer();
    const initial=await ensurePostRenderReview(body,{store:applicationGeneratedAssetStore,rasterizer,provider,model,estimatedCostUsd:config.postRenderQaTargetUsd,maxImages:config.postRenderQaMaxImages});
    const respond=(session:typeof initial)=>{if(session.visualApproved&&session.approvedPackage)registerVisualApprovedPackage(session.approvedPackage);return res.json(req.query.debug==='qa'?{...session,debugQa:{pixelTargetsSent:session.qaPlan.assetTargets.length+(session.qaPlan.compositeTarget?1:0),batchCount:session.qaPlan.batches.length,targetIds:session.qaPlan.batches,assetCoverage:session.qaPlan.assetTargets.map(target=>({targetId:target.id,pixelProvided:target.pixelProvided})),compositeCoverage:Boolean(session.qaPlan.compositeTarget?.pixelProvided),partialCoverageWarning:session.finalReview?.strengths.includes('partial_visual_coverage')??false}}:session)};
    if(initial.outcome!=='partial'||!body.imageAssetSession)return respond(initial);
    const imageProvider=mock?new MockImageGenerationProvider():new OpenAIImageGenerationProvider(createOpenAIClient(config),config.imageEstimatedCostUsd),verificationRaw=mock?new MockPostRenderVisualQaProvider((process.env.AI_VISUAL_QA_VERIFICATION_SCENARIO??'regeneration_success') as never):new OpenAIPostRenderVisualQaProvider(new OpenAIProvider(config),model,config.postRenderQaMaxImages),verification=new BudgetedPostRenderVisualQaProvider(verificationRaw,coordinator,body.projectId,model,config.postRenderQaTargetUsd,config.postRenderQaMaxUsd,config.postRenderQaMaxImages),result=await executeVisualCorrectionLoop(initial,{reviewedDesignPackage:body.reviewedDesignPackage,imageAssetSession:body.imageAssetSession,assetRegistry:body.assetRegistry},{store:applicationGeneratedAssetStore,imageProvider,qaProvider:verification,rasterizer,budget:coordinator,imageModel:mock?'mock-image':config.imageModel,regenLimitUsd:config.imageRegenerationMaxUsd,verificationReserveUsd:config.postRenderQaTargetUsd,maxRounds:config.postRenderMaxRegenerationRounds,maxMb:config.generatedImageMaxMb,storageRetries:config.assetStorageMaxRetries});return respond(result);
  }catch(error){return res.status(422).json({error:error instanceof Error?error.message:'Visual QA failed.'})}});
  return router;
};
