import type {ReviewedDesignPackage} from '../art-director-review/index.js';import type {PixelRect} from '../layout-engine/index.js';
export const RENDER_SCENE_SCHEMA_VERSION='1.0.0' as const;export const RENDERER_POLICY_VERSION='1.0.0' as const;
export type RenderProvenanceSource='reviewed_layout'|'reviewed_route'|'brand_token'|'brand_asset'|'message_content'|'render_rule'|'font_resolution'|'asset_resolution'|'text_fit'|'security_policy';export interface RenderDecisionProvenance{source:RenderProvenanceSource;sourceRef?:string;decision:string}
interface NodeBase{id:string;type:string;rect?:PixelRect;zIndex:number;opacity:number;visible:boolean;transform?:string;clipRef?:string;maskRef?:string;provenance:RenderDecisionProvenance[]}
export interface RenderGroupNode extends NodeBase{type:'group';children:string[]}export interface RenderRectNode extends NodeBase{type:'rect';rect:PixelRect;fill:string;stroke?:string;strokeWidth?:number;radius?:number}export interface RenderEllipseNode extends NodeBase{type:'ellipse';rect:PixelRect;fill:string;stroke?:string;strokeWidth?:number}export interface RenderLineNode extends NodeBase{type:'line';x1:number;y1:number;x2:number;y2:number;stroke:string;strokeWidth:number}export interface RenderPathNode extends NodeBase{type:'path';path:string;fill?:string;stroke?:string;strokeWidth?:number}export interface RenderTextNode extends NodeBase{type:'text';contentRef:string;text:string;rect:PixelRect;fontFamily:string;fallbackFamilies:string[];fontSize:number;minFontSize:number;maxFontSize:number;fontWeight:number;fontStyle?:string;lineHeight:number;letterSpacing:number;textAlign:'left'|'center'|'right';verticalAlign:'top'|'middle'|'bottom';maxLines:number;overflowPolicy:'wrap'|'shrink'|'block';fill:string;textTransform?:'none'|'uppercase'|'lowercase';typographyRole:string;fontResolutionStatus:'exact'|'approved_fallback'|'unresolved';lines:string[]}
export interface RenderImageNode extends NodeBase{type:'image';assetRef:string;rect:PixelRect;fit:'cover'|'contain';focalAnchor:string;crop:string;imageRole:string}export interface RenderClipNode extends NodeBase{type:'clip';shape:'rect'|'ellipse'|'path';value:unknown}export interface RenderMaskNode extends NodeBase{type:'mask';value:unknown}export type RenderNode=RenderGroupNode|RenderRectNode|RenderEllipseNode|RenderLineNode|RenderPathNode|RenderTextNode|RenderImageNode|RenderClipNode|RenderMaskNode;
export interface RenderGradientDefinition{id:string;type:'linear'|'radial';stops:Array<{offset:number;color:string;opacity:number}>;angle?:number;origin?:{x:number;y:number}}export interface RenderDefinitions{gradients:RenderGradientDefinition[];clips:Array<{id:string;rect:PixelRect;radius?:number}>;masks:Array<{id:string;kind:string}>;shadows:Array<{id:string;offsetX:number;offsetY:number;blur:number;spread:number;opacity:number}>}
export type AssetSource='user_upload'|'brand_asset'|'generated'|'system'|'derived';export interface RenderAsset{id:string;source:AssetSource;type:'raster'|'vector'|'icon'|'generated_image';mediaType:string;width?:number;height?:number;fingerprint:string;status:'available'|'unavailable'|'invalid';provenance:string[];backingRef?:string}
export interface AssetRequirement{id:string;role:'official_logo'|'uploaded_product'|'uploaded_photo'|'photography'|'illustration'|'3d_visual'|'texture'|'graphic_device'|'icon'|'background_visual';required:boolean;targetRect:PixelRect;desiredType:string;sourcePreference:AssetSource[];visualIntent:string;imageStrategy?:unknown;focalAnchor?:string;transparencyPreference?:string;contentPolicy:{no_text:boolean;no_logo:boolean;no_brand_marks:boolean;no_ui_text:boolean;no_watermark:boolean};status:'resolved'|'missing'|'unsupported';assetRef?:string}
export interface RenderAssetManifest{assets:RenderAsset[];requirements:AssetRequirement[]}export interface ProjectAssetRegistry{projectId:string;assets:RenderAsset[]}export interface AssetBinaryResolver{resolve(asset:RenderAsset):Promise<Uint8Array|undefined>}export class MemoryAssetBinaryResolver implements AssetBinaryResolver{constructor(private binaries=new Map<string,Uint8Array>()){}async resolve(a:RenderAsset){return this.binaries.get(a.id)}}export interface BrowserProjectAssetResolver extends AssetBinaryResolver{}
export interface RenderReadiness{status:'ready'|'partial'|'blocked';renderableWithPlaceholders:boolean;resolvedAssets:string[];missingRequiredAssets:string[];missingOptionalAssets:string[];fontIssues:string[];textFitIssues:string[];securityIssues:string[];geometryIssues:string[];productionReady:boolean}
export interface RenderScene{schemaVersion:typeof RENDER_SCENE_SCHEMA_VERSION;sceneId:string;projectId:string;width:number;height:number;background:{type:'solid'|'gradient'|'image_slot';value:string};nodes:RenderNode[];definitions:RenderDefinitions;assetManifest:RenderAssetManifest;source:{reviewSessionId:string;layoutId:string;routeId:string};readiness:RenderReadiness;warnings:string[];provenance:RenderDecisionProvenance[]}
export interface RenderDocument{documentId:string;projectId:string;scenes:RenderScene[];formatFamily?:string}export interface RenderedSvgArtifact{artifactId:string;projectId:string;sceneId:string;mimeType:'image/svg+xml';width:number;height:number;svg:string;checksum:string;readiness:RenderReadiness;sourceVersions:Record<string,string|undefined>}
export interface RenderSession{schemaVersion:typeof RENDER_SCENE_SCHEMA_VERSION;sessionId:string;projectId:string;createdAt:string;inputFingerprint:string;reviewedDesignPackageRef:string;renderDocument:RenderDocument;artifacts:RenderedSvgArtifact[];readiness:RenderReadiness;status:'ready'|'partial'|'failed';warnings:string[];cost:0;sourceVersions:Record<string,string|undefined>}
export interface CreateRenderSessionRequest{projectId:string;reviewedDesignPackage:ReviewedDesignPackage;assetRegistry:ProjectAssetRegistry;destinationTool?:string;existingSession?:RenderSession;fontAvailability?:string[];designSpecification?:string}
export interface Rasterizer{rasterize(svg:string,options:{width:number;height:number;mediaType:string}):Promise<Uint8Array>}
