// @ts-nocheck -- executable integration microtests intentionally use minimal domain fixtures.
import {strict as assert} from 'node:assert';import {createHash} from 'node:crypto';import {createImageBudgetPreflight,generateRequiredAssets,materializeSvgAssets} from '../../application/image-assets/index.js';import {createGeneratedAssetRef,parseGeneratedAssetRef,reconcileGeneratedAssetBacking,type ImageGenerationJob} from '../../domain/image-assets/index.js';import type {AssetRequirement,RenderSession} from '../../domain/render-engine/index.js';import {InMemoryBudgetStore} from '../ai/budget/budget-tracker.js';import {ProjectAIBudgetCoordinator} from '../ai/budget/project-coordinator.js';import {InMemoryGeneratedAssetStore,MockDurableGeneratedAssetStore,MockImageGenerationProvider,UnavailableGeneratedAssetStore,createGeneratedAssetStore} from './index.js';
const bytes=Uint8Array.from([137,80,78,71,13,10,26,10,0,0,0,13]),checksum=createHash('sha256').update(bytes).digest('hex'),ref=createGeneratedAssetRef('blob-private','project_a',checksum,'png');assert.equal(parseGeneratedAssetRef(ref,'project_a').pathname,`projects/project_a/generated/${checksum}.png`);assert.throws(()=>parseGeneratedAssetRef(ref,'project_b'));assert.throws(()=>parseGeneratedAssetRef('blob-private://project_a/../../x.png','project_a'));
const backend=new Map<string,Uint8Array>(),one=new MockDurableGeneratedAssetStore(backend),stored=await one.put({projectId:'project_a',assetId:'a',bytes,mediaType:'image/png',checksum}),two=new MockDurableGeneratedAssetStore(backend);assert.deepEqual(await two.get(stored,'project_a'),bytes);assert(await two.exists(stored,'project_a'));assert.rejects(()=>two.get(stored,'project_b'));const handle=await two.createReadHandle!(stored,'project_a','image/png',300);assert(Date.parse(handle.expiresAt)>Date.now());await two.delete(stored,'project_a');assert(!(await one.exists(stored,'project_a')));
assert.equal(createGeneratedAssetStore({NODE_ENV:'development'}).kind,'memory');assert.equal(createGeneratedAssetStore({NODE_ENV:'production'}).kind,'unavailable');assert.equal(createGeneratedAssetStore({NODE_ENV:'production',ASSET_ALLOW_INMEMORY_STORAGE:'true'}).kind,'memory');
const job=(id:string):ImageGenerationJob=>({jobId:id,projectId:'p',requirementId:id,fingerprint:id,model:'mock',quality:'standard',size:{width:16,height:16},outputFormat:'png',promptPlan:{} as never}),jobs=[job('mandatory'),job('optional')],estimates=new Map([['mandatory',.2],['optional',.2]]),snapshot={remainingUsd:.3,monthlyRemainingUsd:1,stages:{image_generation:{spentUsd:0,reservedUsd:0}}};const plan=createImageBudgetPreflight(jobs,estimates,new Set(['mandatory']),snapshot,.35);assert(plan.mandatoryFeasible);assert.deepEqual(plan.admittedJobs.map(x=>x.jobId),['mandatory']);assert.deepEqual(createImageBudgetPreflight(jobs,estimates,new Set(['mandatory','optional']),snapshot,.35).admittedJobs,[]);
const requirement:AssetRequirement={id:'requirement_hero',role:'photography',required:true,targetRect:{x:0,y:0,width:16,height:16},desiredType:'raster',sourcePreference:['generated'],visualIntent:'visual',contentPolicy:{no_text:true,no_logo:true,no_brand_marks:true,no_ui_text:true,no_watermark:true},status:'missing'};const format={id:'f',label:'f',usage:'general',width:16,height:16,aspectRatio:1,aspectLabel:'1:1',orientation:'square',category:'custom',baseSafeArea:{top:0,right:0,bottom:0,left:0},recommendedGrid:{kind:'column',columnRange:[1,1]},aliases:[]},layout={layoutId:'l',projectId:'p',selectedRouteId:'r',format,canvas:{width:16,height:16},elements:[],layers:{order:[]}} as never,pkg={projectId:'p',reviewSessionId:'review',approvalStatus:'approved',creativeRoute:{id:'r',copyHierarchy:[]},layoutPlan:layout,sourceVersions:{}} as never,render={sessionId:'render',projectId:'p',renderDocument:{scenes:[{assetManifest:{requirements:[requirement]}}]},readiness:{}} as never as RenderSession;
const run=async(store:InMemoryGeneratedAssetStore|MockDurableGeneratedAssetStore|UnavailableGeneratedAssetStore,provider:MockImageGenerationProvider,production=false)=>{const budgetStore=new InMemoryBudgetStore(),budget=new ProjectAIBudgetCoordinator(budgetStore,{projectLimitUsd:.75,monthlyLimitUsd:15,safetyFactor:1,ttlSeconds:600}),result=await generateRequiredAssets({projectId:'p',reviewedDesignPackage:pkg,renderSession:render,assetRegistry:{projectId:'p',assets:[]}},{provider,store,budget,model:'mock-image',targetUsd:.22,limitUsd:.35,maxMb:20,production,storageMaxRetries:1});return{result,budget}};
class CountingProvider extends MockImageGenerationProvider{calls=0;override async generate(j:ImageGenerationJob){this.calls++;return super.generate(j)}}const blockedProvider=new CountingProvider(),blocked=await run(new InMemoryGeneratedAssetStore(),blockedProvider,true);assert.equal(blockedProvider.calls,0);assert.equal(blocked.result.failures[0]?.reason,'storage_unavailable');
class InvalidProvider extends CountingProvider{override async generate(j:ImageGenerationJob){const r=await super.generate(j);return{...r,bytes:new Uint8Array([1,2,3]),actualCostUsd:.07}}}const invalid=await run(new MockDurableGeneratedAssetStore(),new InvalidProvider(),true);assert.equal(invalid.result.cost.actualUsd,.07);assert.equal((await invalid.budget.snapshot('p')).spentUsd,.07);assert.equal(invalid.result.failures[0]?.reason,'generated_output_invalid');
class FailingStore extends MockDurableGeneratedAssetStore{puts=0;override async put():Promise<string>{this.puts++;throw new Error('down')}}const failingStore=new FailingStore(),storageFailure=await run(failingStore,new CountingProvider(),true);assert.equal(failingStore.puts,2);assert.equal(storageFailure.result.cost.actualUsd,.01);assert.equal(storageFailure.result.failures[0]?.reason,'generated_asset_storage_failed');
const canonical={artifactId:'a',checksum:'canonical',svg:'<svg><image href="asset://asset1"/></svg>'} as never,deliveryStore=new MockDurableGeneratedAssetStore();const deliveryRef=await deliveryStore.put({projectId:'p',assetId:'asset1',bytes,mediaType:'image/png',checksum});const materialized=await materializeSvgAssets(canonical,{projectId:'p',assets:[{id:'asset1',source:'generated',type:'generated_image',mediaType:'image/png',fingerprint:'f',status:'available',provenance:[],backingRef:deliveryRef}]},deliveryStore,300);assert(canonical.svg.includes('asset://'));assert(!materialized.svg.includes('asset://'));assert.equal(materialized.canonicalChecksum,'canonical');assert.equal((await reconcileGeneratedAssetBacking({status:'available',backingRef:deliveryRef} as never,'p',deliveryStore)).status,'available');
console.log('Durable asset storage validation passed: isolation, cold start, delivery, preflight and billable downstream failures.');
