import {del,get,head,issueSignedToken,presignUrl,put} from '@vercel/blob';import {createHash} from 'node:crypto';import {createGeneratedAssetRef,parseGeneratedAssetRef,type GeneratedAssetStore} from '../../domain/image-assets/index.js';
export class VercelBlobGeneratedAssetStore implements GeneratedAssetStore{
  readonly kind='durable' as const;readonly capabilities={durable:true,private:true,signedReads:true,atomicObjectNames:true};
  async put(i:{projectId:string;bytes:Uint8Array;mediaType:string;checksum:string}){if(createHash('sha256').update(i.bytes).digest('hex')!==i.checksum)throw new Error('Generated asset checksum mismatch.');const ext=i.mediaType==='image/jpeg'?'jpg':i.mediaType==='image/webp'?'webp':'png',ref=createGeneratedAssetRef('blob-private',i.projectId,i.checksum,ext),{pathname}=parseGeneratedAssetRef(ref,i.projectId);let existing;try{existing=await head(pathname)}catch{existing=undefined}if(existing){if(existing.contentType!==i.mediaType)throw new Error('Existing backing metadata mismatch.');return ref}await put(pathname,Buffer.from(i.bytes),{access:'private',addRandomSuffix:false,allowOverwrite:false,contentType:i.mediaType,cacheControlMaxAge:31536000});return ref}
  async get(ref:string,projectId:string){const parsed=parseGeneratedAssetRef(ref,projectId),result=await get(parsed.pathname,{access:'private'});if(!result||result.statusCode!==200)return undefined;const bytes=new Uint8Array(await new Response(result.stream).arrayBuffer());if(createHash('sha256').update(bytes).digest('hex')!==parsed.checksum)throw new Error('Backing asset checksum mismatch.');return bytes}
  async exists(ref:string,projectId:string){try{await head(parseGeneratedAssetRef(ref,projectId).pathname);return true}catch{return false}}
  async delete(ref:string,projectId:string){await del(parseGeneratedAssetRef(ref,projectId).pathname)}
  async health(){try{if(!process.env.BLOB_STORE_ID&&!process.env.BLOB_READ_WRITE_TOKEN)return{status:'degraded' as const,store:'durable' as const,private:true,signedReads:true};await issueSignedToken({pathname:'projects/health/*',operations:['head'],validUntil:Date.now()+60_000});return{status:'ok' as const,store:'durable' as const,private:true,signedReads:true}}catch{return{status:'degraded' as const,store:'durable' as const,private:true,signedReads:true}}}
  async createReadHandle(ref:string,projectId:string,mediaType:string,ttl:number){const {pathname}=parseGeneratedAssetRef(ref,projectId),validUntil=Date.now()+ttl*1000,token=await issueSignedToken({pathname,operations:['get'],validUntil}),result=await presignUrl(token,{access:'private',operation:'get',pathname,validUntil});return{url:result.presignedUrl,expiresAt:new Date(validUntil).toISOString(),mediaType}}
}
