import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import sharp from "sharp";
import {finalizeProjectSourceAsset,reconcileProjectSourceAsset,resolveProjectSourceRegistry} from "../../application/source-assets/index.js";
import {createMockSourceAssetDatabase,MockProjectSourceAssetRepository} from "../../infrastructure/source-assets/repository.js";
import {createMockSourceAssetBacking,MockDurableProjectSourceAssetStore} from "../../infrastructure/source-assets/store.js";
import {buildProjectSourceAssetRegistry,createProjectSourceAssetRef,parseProjectSourceAssetRef,safeSourceAssetSummary,validateProjectSourceImage} from "./index.js";
const png=new Uint8Array(await sharp({create:{width:32,height:24,channels:4,background:{r:20,g:40,b:60,alpha:1}}}).png().toBuffer()),checksum=createHash("sha256").update(png).digest("hex"),db=createMockSourceAssetDatabase(),backing=createMockSourceAssetBacking(),storeA=new MockDurableProjectSourceAssetStore(backing),repoA=new MockProjectSourceAssetRepository(db);
await assert.rejects(()=>validateProjectSourceImage({bytes:png,declaredMediaType:"image/jpeg",role:"visual_reference",maxBytes:1e6,maxPixels:1e6}),/media type/);
await assert.rejects(()=>validateProjectSourceImage({bytes:new Uint8Array([1,2,3]),declaredMediaType:"image/png",role:"visual_reference",maxBytes:1e6,maxPixels:1e6}));
await assert.rejects(()=>validateProjectSourceImage({bytes:png,declaredMediaType:"image/png",role:"visual_reference",maxBytes:2,maxPixels:1e6}),/size/);
await assert.rejects(()=>validateProjectSourceImage({bytes:png,declaredMediaType:"image/png",role:"visual_reference",maxBytes:1e6,maxPixels:100}),/pixel|dimensions|Input image/i);
assert.throws(()=>parseProjectSourceAssetRef(createProjectSourceAssetRef("project-a",checksum,"png"),"project-b"),/cross-project/);
await storeA.put({projectId:"project-a",bytes:png,mediaType:"image/png",checksum});
const summary=await finalizeProjectSourceAsset({projectId:"project-a",role:"official_logo",operationId:"upload:logo:1",originalFilename:"logo.png",mediaType:"image/png",byteSize:png.byteLength,checksum},{repository:repoA,store:storeA,maxBytes:1e6,maxPixels:1e6});
assert(!("backingRef" in summary));assert.equal(summary.width,32);
const duplicate=await finalizeProjectSourceAsset({projectId:"project-a",role:"official_logo",operationId:"upload:logo:retry",originalFilename:"logo-copy.png",mediaType:"image/png",byteSize:png.byteLength,checksum},{repository:repoA,store:storeA,maxBytes:1e6,maxPixels:1e6});assert.equal(duplicate.assetId,summary.assetId);
const repoB=new MockProjectSourceAssetRepository(db),storeB=new MockDurableProjectSourceAssetStore(backing),restored=await repoB.get("project-a",summary.assetId);assert(restored);assert.equal((await reconcileProjectSourceAsset(restored,storeB)).status,"available");
const registry=await resolveProjectSourceRegistry("project-a",[summary.assetId],repoB,storeB);assert.equal(registry.registry.assets[0]?.provenance[1],"official_logo");assert.equal(registry.registry.assets[0]?.source,"brand_asset");assert(!("backingRef" in safeSourceAssetSummary(restored)));
const roleRegistry=buildProjectSourceAssetRegistry("project-a",[{...restored,assetId:"ref",role:"visual_reference"},{...restored,assetId:"product",role:"product_image"}]);assert(!roleRegistry.registry.assets.some(asset=>asset.id==="ref"));assert(roleRegistry.registry.assets.find(asset=>asset.id==="product")?.provenance.includes("uploaded_product"));
backing.objects={};assert.equal((await reconcileProjectSourceAsset(restored,storeB)).status,"unavailable");
console.log("Source asset validation passed: image policy, MIME spoofing, private refs, idempotency, cold-start restore, renderer provenance and missing backing.");
