import type {ProjectAssetRegistry} from "../render-engine/index.js";
export const SOURCE_ASSET_SCHEMA_VERSION="1.0.0" as const;
export const SOURCE_ASSET_POLICY_VERSION="1.0.0" as const;
export type ProjectSourceAssetRole="visual_reference"|"official_logo"|"product_image"|"brand_photo"|"graphic_asset";
export type ProjectSourceAssetStatus="available"|"invalid"|"unavailable"|"superseded"|"removed";
export interface ProjectSourceAsset{schemaVersion:typeof SOURCE_ASSET_SCHEMA_VERSION;assetId:string;projectId:string;operationId:string;role:ProjectSourceAssetRole;originalFilename:string;mediaType:"image/jpeg"|"image/png"|"image/webp";byteSize:number;width?:number;height?:number;aspectRatio?:number;checksum:string;backingRef:string;status:ProjectSourceAssetStatus;supersedesAssetId?:string;createdAt:string;updatedAt:string;metadata:{hasAlpha?:boolean;warning?:string}}
export type ProjectSourceAssetSummary=Omit<ProjectSourceAsset,"backingRef"|"operationId"|"metadata">&{filename:string;hasAlpha?:boolean;warning?:string};
export interface ProjectSourceAssetStoreCapabilities{durable:boolean;private:true;signedReads:boolean;directClientUpload:boolean}
export interface ProjectSourceAssetStore{readonly kind:"memory"|"durable"|"unavailable";readonly capabilities:ProjectSourceAssetStoreCapabilities;put(input:{projectId:string;bytes:Uint8Array;mediaType:string;checksum:string}):Promise<string>;get(ref:string,projectId:string):Promise<Uint8Array|undefined>;exists(ref:string,projectId:string):Promise<boolean>;delete(ref:string,projectId:string):Promise<void>;createReadHandle?(ref:string,projectId:string,mediaType:string,ttlSeconds:number):Promise<{url:string;expiresAt:string;mediaType:string}>;health():Promise<{status:"ok"|"degraded";kind:"durable"|"memory"|"unavailable";private:true}>}
export interface ProjectSourceAssetRepository{save(asset:ProjectSourceAsset):Promise<ProjectSourceAsset>;get(projectId:string,assetId:string):Promise<ProjectSourceAsset|undefined>;listByProject(projectId:string):Promise<ProjectSourceAsset[]>;findByChecksum(projectId:string,checksum:string,role?:ProjectSourceAssetRole):Promise<ProjectSourceAsset|undefined>;markUnavailable(projectId:string,assetId:string):Promise<void>;markSuperseded(projectId:string,assetId:string,replacementId:string):Promise<void>;health():Promise<{status:"ok"|"degraded";kind:"durable"|"memory"|"unavailable"}>}
export interface SourceAssetUploadDescriptor{projectId:string;role:ProjectSourceAssetRole;operationId:string;originalFilename:string;mediaType:string;byteSize:number;checksum:string}
export interface SourceAssetRegistryResult{registry:ProjectAssetRegistry;unavailableAssetIds:string[]}
