import type {AssetRequirement,ProjectAssetRegistry,RenderAsset,RenderSession} from '../render-engine/index.js';
export const IMAGE_ASSET_SCHEMA_VERSION='1.0.0' as const;
export type ImageAssetQuality='draft'|'standard'|'final';
export interface ImageProviderCapabilities{models:string[];formats:Array<'png'|'jpeg'|'webp'>;qualities:ImageAssetQuality[];transparentBackground:boolean;arbitrarySize:boolean;minEdge:number;maxEdge:number;edgeMultiple:number;minAspectRatio:number;maxAspectRatio:number}
export interface ImagePromptPlan{schemaVersion:typeof IMAGE_ASSET_SCHEMA_VERSION;requirementId:string;role:AssetRequirement['role'];subject:string;composition:string;visualLanguage:string;lighting:string;materials:string;focalRegion:{x:number;y:number};protectedRegions:Array<{x:number;y:number;width:number;height:number}>;negativeSpaceRegions:Array<{x:number;y:number;width:number;height:number}>;constraints:string[];forbiddenContent:string[];referenceImagePolicy:'none'|'explicitly_authorized'}
export interface ImageGenerationJob{jobId:string;projectId:string;requirementId:string;fingerprint:string;model:string;quality:ImageAssetQuality;size:{width:number;height:number};outputFormat:'png'|'jpeg'|'webp';promptPlan:ImagePromptPlan}
export interface GeneratedImageAsset extends RenderAsset{source:'generated';type:'generated_image';width:number;height:number;backingRef:string;checksum:string;requirementId:string;model:string;quality:ImageAssetQuality;createdAt:string}
export interface ImageAssetSession{schemaVersion:typeof IMAGE_ASSET_SCHEMA_VERSION;sessionId:string;projectId:string;createdAt:string;sourceRenderSessionId:string;jobs:ImageGenerationJob[];generatedAssets:GeneratedImageAsset[];reusedAssets:string[];unresolvedRequirements:string[];registry:ProjectAssetRegistry;renderSession:RenderSession;status:'ready'|'partial'|'blocked';visualQaStatus:'qaPending'|'passed'|'failed';cost:{estimatedUsd:number;actualUsd?:number;targetUsd:number;limitUsd:number}}
export interface ImageGenerationResult{bytes:Uint8Array;mediaType:'image/png'|'image/jpeg'|'image/webp';width:number;height:number;model:string;requestId:string;durationMs:number;usage?:{inputTokens?:number;outputTokens?:number};actualCostUsd?:number}
export interface ImageGenerationProvider{readonly id:string;capabilities():ImageProviderCapabilities;estimateCost(job:ImageGenerationJob):number;generate(job:ImageGenerationJob):Promise<ImageGenerationResult>}
export interface GeneratedAssetStore{put(input:{projectId:string;assetId:string;bytes:Uint8Array;mediaType:string;checksum:string}):Promise<string>;get(bytesRef:string):Promise<Uint8Array|undefined>}
