import type {AssetRequirement,ProjectAssetRegistry,RenderAsset,RenderSession} from '../render-engine/index.js';
export const IMAGE_ASSET_SCHEMA_VERSION='1.0.0' as const;
export type ImageAssetQuality='draft'|'standard'|'final';
export interface ImageProviderCapabilities{models:string[];formats:Array<'png'|'jpeg'|'webp'>;qualities:ImageAssetQuality[];transparentBackground:boolean;arbitrarySize:boolean;minEdge:number;maxEdge:number;edgeMultiple:number;minAspectRatio:number;maxAspectRatio:number}
export interface ImagePromptPlan{schemaVersion:typeof IMAGE_ASSET_SCHEMA_VERSION;requirementId:string;role:AssetRequirement['role'];subject:string;composition:string;visualLanguage:string;lighting:string;materials:string;focalRegion:{x:number;y:number};protectedRegions:Array<{x:number;y:number;width:number;height:number}>;negativeSpaceRegions:Array<{x:number;y:number;width:number;height:number}>;constraints:string[];forbiddenContent:string[];referenceImagePolicy:'none'|'explicitly_authorized'}
export interface ImageGenerationJob{jobId:string;projectId:string;requirementId:string;fingerprint:string;model:string;quality:ImageAssetQuality;size:{width:number;height:number};outputFormat:'png'|'jpeg'|'webp';promptPlan:ImagePromptPlan}
export interface GeneratedImageAsset extends RenderAsset{source:'generated';type:'generated_image';width:number;height:number;backingRef:string;checksum:string;requirementId:string;model:string;quality:ImageAssetQuality;createdAt:string}
export interface ImageAssetSession{schemaVersion:typeof IMAGE_ASSET_SCHEMA_VERSION;sessionId:string;projectId:string;createdAt:string;sourceRenderSessionId:string;jobs:ImageGenerationJob[];generatedAssets:GeneratedImageAsset[];reusedAssets:string[];unresolvedRequirements:string[];failures:Array<{jobId?:string;reason:ImageAssetFailureReason;message:string}>;budgetPlan:ImageBudgetPlan;registry:ProjectAssetRegistry;renderSession:RenderSession;status:'ready'|'partial'|'blocked';visualQaStatus:'qaPending'|'passed'|'failed';cost:{estimatedUsd:number;actualUsd?:number;targetUsd:number;limitUsd:number}}
export interface ImageGenerationResult{bytes:Uint8Array;mediaType:'image/png'|'image/jpeg'|'image/webp';width:number;height:number;model:string;requestId:string;durationMs:number;usage?:{inputTokens?:number;outputTokens?:number};actualCostUsd?:number}
export interface ImageGenerationProvider{readonly id:string;capabilities():ImageProviderCapabilities;estimateCost(job:ImageGenerationJob):number;generate(job:ImageGenerationJob):Promise<ImageGenerationResult>}
export interface GeneratedAssetStoreCapabilities{durable:boolean;private:boolean;signedReads:boolean;atomicObjectNames:boolean}
export interface AssetReadHandle{url:string;expiresAt:string;mediaType:string}
export interface GeneratedAssetStore{readonly kind:'memory'|'durable'|'unavailable';readonly capabilities:GeneratedAssetStoreCapabilities;put(input:{projectId:string;assetId:string;bytes:Uint8Array;mediaType:string;checksum:string}):Promise<string>;get(bytesRef:string,projectId:string):Promise<Uint8Array|undefined>;exists(bytesRef:string,projectId:string):Promise<boolean>;delete(bytesRef:string,projectId:string):Promise<void>;health():Promise<{status:'ok'|'degraded';store:'durable'|'memory'|'unavailable';private:boolean;signedReads:boolean}>;createReadHandle?(bytesRef:string,projectId:string,mediaType:string,ttlSeconds:number):Promise<AssetReadHandle>}
export type ImageAssetFailureReason='storage_unavailable'|'budget_plan_infeasible'|'provider_rejected'|'provider_timeout_unknown'|'generated_output_invalid'|'generated_asset_storage_failed'|'backing_asset_missing'|'render_rebuild_failed';
export interface ImageBudgetPlan{mandatoryJobs:ImageGenerationJob[];optionalJobs:ImageGenerationJob[];mandatoryEstimatedUsd:number;optionalEstimatedUsd:number;projectRemainingUsd:number;monthlyRemainingUsd:number;stageRemainingUsd:number;mandatoryFeasible:boolean;optionalFeasible:boolean;admittedJobs:ImageGenerationJob[];skippedJobs:ImageGenerationJob[];reason?:'budget_plan_infeasible'}
