import {createHash} from 'node:crypto';
import type {BrandIntelligenceSession} from '../../domain/brand-intelligence/index.js';
import {validateCreativeDirectionSession,type CreativeDirectionSession} from '../../domain/creative-direction/index.js';
import {LAYOUT_PLAN_SCHEMA_VERSION,createKeepTogetherGroups,createLayoutContent,rankLayoutArchetypes,resolveCanvas,resolveFormatDefinition,resolveLayoutIntent,selectBestLayoutCandidate,solveLayoutCandidate,type FormatContext,type FormatDefinition,type LayoutDocument,type LayoutIntelligenceSession} from '../../domain/layout-engine/index.js';
import type {ReferenceIntelligenceSession} from '../reference-intelligence/index.js';
export interface CreateLayoutIntelligenceRequest {projectId:string;creativeDirection:CreativeDirectionSession;brandIntelligence?:BrandIntelligenceSession;referenceIntelligence?:ReferenceIntelligenceSession;format:string|{width:number;height:number;id?:string};formatContext?:FormatContext;destinationTool:string;existingSession?:LayoutIntelligenceSession}
const stable=(v:unknown):string=>Array.isArray(v)?`[${v.map(stable).join(',')}]`:v&&typeof v==='object'?`{${Object.entries(v as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${stable(x)}`).join(',')}}`:JSON.stringify(v);
export const fingerprintLayoutInput=(request:CreateLayoutIntelligenceRequest,format:FormatDefinition)=>createHash('sha256').update(stable({creativeFingerprint:request.creativeDirection.inputFingerprint,routeId:request.creativeDirection.selectedRouteId,messages:request.creativeDirection.strategicFrame.messageHierarchy,brand:request.brandIntelligence?.inputFingerprint,reference:request.referenceIntelligence?.sessionId,format:format.id,formatContext:request.formatContext,dimensions:[format.width,format.height],destinationTool:request.destinationTool,schema:LAYOUT_PLAN_SCHEMA_VERSION})).digest('hex');
export const createLayoutIntelligence=(request:CreateLayoutIntelligenceRequest):LayoutIntelligenceSession=>{
  if(request.projectId!==request.creativeDirection.projectId||request.creativeDirection.status!=='ready'||!request.creativeDirection.selectedRoute||!validateCreativeDirectionSession(request.creativeDirection))throw new Error('Layout requires a ready and compatible Creative Direction session.');
  const format=resolveFormatDefinition(request.format,request.formatContext),fingerprint=fingerprintLayoutInput(request,format);if(request.existingSession?.inputFingerprint===fingerprint&&request.existingSession.status==='ready')return request.existingSession;
  const brand=request.brandIntelligence?.brandDNA,route=request.creativeDirection.selectedRoute,canvas=resolveCanvas(format,{minimum:format.baseSafeArea,maximum:{top:.2,right:.2,bottom:.2,left:.2},platformInsets:format.platformInsets}),intent=resolveLayoutIntent(route,format,brand),content=createLayoutContent(route,brand),ranked=rankLayoutArchetypes(route,intent,format,content,brand).slice(0,3),candidates=ranked.map((a,i)=>({id:`candidate_${i+1}`,archetype:a.id,plan:solveLayoutCandidate({projectId:request.projectId,creativeSessionId:request.creativeDirection.sessionId,route,canvas,format,archetype:a.id,intent,content,brand,variant:i+1})}));
  try{const selected=selectBestLayoutCandidate(candidates);const document:LayoutDocument={documentId:`document_${fingerprint.slice(0,16)}`,projectId:request.projectId,formatFamily:format.platform==='meta'?'meta_ads_family':format.category,frames:[selected.plan],keepTogetherGroups:createKeepTogetherGroups(route.copyHierarchy)};return{schemaVersion:LAYOUT_PLAN_SCHEMA_VERSION,sessionId:`layout_session_${fingerprint.slice(0,20)}`,projectId:request.projectId,createdAt:new Date().toISOString(),inputFingerprint:fingerprint,layoutDocument:document,candidates,selectedLayoutId:selected.plan.layoutId,quality:selected.plan.quality,warnings:selected.plan.warnings,status:'ready',sourceVersions:{creativeDirection:request.creativeDirection.schemaVersion,brandDNA:request.brandIntelligence?.schemaVersions.brandDNA,referenceDNA:request.referenceIntelligence?.designDNASchemaVersion,layoutSchema:LAYOUT_PLAN_SCHEMA_VERSION},cost:0}}catch(error){return{schemaVersion:LAYOUT_PLAN_SCHEMA_VERSION,sessionId:`layout_session_${fingerprint.slice(0,20)}`,projectId:request.projectId,createdAt:new Date().toISOString(),inputFingerprint:fingerprint,candidates,warnings:['No candidate passed hard layout gates.'],status:'failed',failureReason:error instanceof Error?error.message:'Layout solving failed.',sourceVersions:{creativeDirection:request.creativeDirection.schemaVersion,brandDNA:request.brandIntelligence?.schemaVersions.brandDNA,referenceDNA:request.referenceIntelligence?.designDNASchemaVersion,layoutSchema:LAYOUT_PLAN_SCHEMA_VERSION},cost:0}}
};
