import type {ArtDirectionRoute} from '../creative-direction/index.js';
import type {BrandDNA} from '../brand-intelligence/index.js';
import type {FormatDefinition,LayoutArchetypeId,LayoutContentBlock,LayoutIntent,RankedArchetype} from './types.js';

export const resolveLayoutIntent=(route:ArtDirectionRoute,format:FormatDefinition,brand?:BrandDNA):LayoutIntent=>{
  const composition=`${route.compositionStrategy} ${route.spatialStrategy.layering} ${route.typographyBehavior.alignmentCharacter}`.toLowerCase();
  let hero:LayoutIntent['heroRegionPreference']=route.heroStrategy==='typography'?'center':format.orientation==='landscape'?'right':format.category==='social_story'?'top':'bottom';
  if(route.heroStrategy==='mixed'&&format.orientation==='landscape')hero='left';
  const overlay=/overlay|overlap|layer/.test(composition),dense=/dense|compact|compressed/.test(`${route.spatialStrategy.density} ${route.spatialStrategy.compression}`),density=dense?.72:(brand?.compositionCharacter?.visualDensity??.45);
  return{heroRegionPreference:overlay?'full_bleed':hero,textRegionPreference:overlay?'overlay':hero==='right'?'left':hero==='left'?'right':hero==='top'?'bottom':'top',axisPreference:format.orientation==='landscape'?'horizontal':'vertical',balancePreference:/symmetr|center/.test(composition)?'symmetric':'asymmetric',density,negativeSpaceTarget:Math.max(.12,Math.min(.55,brand?.compositionCharacter?.negativeSpacePreference??(1-density)*.48)),overlapTolerance:overlay?.65:.12,layeringIntent:overlay?'layered':route.spatialStrategy.layering.toLowerCase().includes('deep')?'deep':'flat',alignmentCharacter:route.typographyBehavior.alignmentCharacter.toLowerCase().includes('optical')?'optical':'strict',modularity:brand?.compositionCharacter?.modularity??.5,focalOrder:[route.heroStrategy==='typography'?'headline':route.heroStrategy==='data'?'data':'hero_image','headline','subheadline','cta']};
};
const ids:LayoutArchetypeId[]=['split_hero','editorial_asymmetric','centered_statement','typographic_poster','data_dominant','full_bleed_overlay','modular_cards','product_stage','framed_editorial','stacked_story','balanced_dual_zone'];
export const rankLayoutArchetypes=(route:ArtDirectionRoute,intent:LayoutIntent,format:FormatDefinition,content:LayoutContentBlock[],brand?:BrandDNA):RankedArchetype[]=>ids.map(id=>{let score=.25;const reasons:string[]=[];if(id==='split_hero'&&format.orientation==='landscape'){score+=.45;reasons.push('landscape dual allocation')}if(id==='stacked_story'&&format.category==='social_story'){score+=.55;reasons.push('vertical sequential format')}if(id==='typographic_poster'&&route.heroStrategy==='typography'){score+=.65;reasons.push('typography is hero')}if(id==='data_dominant'&&route.heroStrategy==='data'){score+=.65;reasons.push('data is hero')}if(id==='product_stage'&&route.heroStrategy==='product'){score+=.55;reasons.push('product is hero')}if(id==='full_bleed_overlay'&&intent.overlapTolerance>.5){score+=.55;reasons.push('approved overlap')}if(id==='centered_statement'&&intent.balancePreference==='symmetric'){score+=.45;reasons.push('symmetric balance')}if(id==='editorial_asymmetric'&&intent.balancePreference==='asymmetric'){score+=.4;reasons.push('asymmetric balance')}if(id==='modular_cards'&&intent.modularity>.65){score+=.45;reasons.push('modular brand character')}if(id==='framed_editorial'&&(brand?.compositionCharacter?.editorialness??0)>.6){score+=.45;reasons.push('editorial brand character')}if(id==='balanced_dual_zone'&&content.length>5){score+=.3;reasons.push('content quantity')}return{id,score:Math.min(1,score),reasons}}).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));
