import type {ArtDirectionRoute,MessageHierarchyItem} from '../creative-direction/index.js';import type {BrandDNA} from '../brand-intelligence/index.js';import type {ContentRole,LayoutContentBlock} from './types.js';
const mapRole=(role:MessageHierarchyItem['role']):ContentRole=>role==='hook'?'eyebrow':role==='support'?'body':role;
export const createLayoutContent=(route:ArtDirectionRoute,brand?:BrandDNA):LayoutContentBlock[]=>{
  const content:LayoutContentBlock[]=route.copyHierarchy.map(item=>({id:`el_${item.id}`,role:mapRole(item.role),contentRef:item.id,priority:item.priority,mandatory:['headline','offer','legal'].includes(item.role)||item.source==='explicit',visualImportance:item.visualImportance,preferredRegion:item.priority<=1?'primary_message':'secondary_message',maxLines:item.role==='headline'?4:item.role==='legal'?8:6,canCrop:false,canOverlap:false,canHide:item.source==='inferred'&&item.priority>3,layerRole:item.role==='legal'?'legal':item.role==='cta'?'cta':'content'}));
  if(route.heroStrategy!=='none')content.push({id:'el_hero',role:route.heroStrategy==='typography'?'graphic_device':route.heroStrategy==='human'?'human':route.heroStrategy==='product'?'product':'hero_image',priority:1,mandatory:true,visualImportance:.95,preferredRegion:'hero',canCrop:true,canOverlap:route.spatialStrategy.layering!=='flat',canHide:false,layerRole:'hero'});
  if(route.creativeDevice.name)content.push({id:'el_device',role:'graphic_device',priority:2,mandatory:true,visualImportance:.55,preferredRegion:'supporting_visual',canCrop:true,canOverlap:true,canHide:false,layerRole:'graphic_device'});
  const logo=brand?.logoSystem?.primaryLogo;if(logo?.assetId)content.push({id:'el_logo',role:'logo',assetRef:logo.assetId,priority:2,mandatory:true,visualImportance:.35,preferredRegion:'brand',canCrop:false,canOverlap:false,canHide:false,layerRole:'brand'});
  return content;
};
export const createKeepTogetherGroups=(messages:MessageHierarchyItem[])=>{const refs=(roles:MessageHierarchyItem['role'][])=>(messages.filter(m=>roles.includes(m.role)).map(m=>m.id));return[{id:'offer_qualifier',contentRefs:refs(['offer','legal']),reason:'Offer and qualifier must retain meaning.'},{id:'cta_action',contentRefs:refs(['cta','support']),reason:'CTA and action qualifier belong together.'}].filter(g=>g.contentRefs.length>1)};
