import type {CanvasSpec,CustomFormatDefinition,FormatContext,FormatDefinition,FormatFamily,Insets,NormalizedRect,Orientation,PixelRect,SafeAreaPolicy} from './types.js';
const inset=(v:number):Insets=>({top:v,right:v,bottom:v,left:v});
const generic=(value:Omit<FormatDefinition,'platform'|'usage'|'metadata'>):FormatDefinition=>({...value,usage:'general',metadata:{recommended:true,organic:true}});
export const GENERIC_SQUARE_1080=generic({id:'generic_square_1080',label:'Quadrado genérico 1:1',width:1080,height:1080,aspectRatio:1,aspectLabel:'1:1',orientation:'square',category:'social_square',baseSafeArea:inset(.06),recommendedGrid:{kind:'modular',columnRange:[4,8],rowRange:[6,12]},aliases:['square_1080','Square','Feed Quadrado','1080x1080','1:1']});
export const GENERIC_PORTRAIT_1080_1350=generic({id:'generic_portrait_1080_1350',label:'Vertical genérico 4:5',width:1080,height:1350,aspectRatio:.8,aspectLabel:'4:5',orientation:'portrait',category:'social_portrait',baseSafeArea:inset(.055),recommendedGrid:{kind:'hybrid',columnRange:[4,8],rowRange:[8,14]},aliases:['portrait_4_5','Portrait','Feed Retrato','1080x1350','4:5']});
export const GENERIC_VERTICAL_1080_1920=generic({id:'generic_vertical_1080_1920',label:'Vertical genérico 9:16',width:1080,height:1920,aspectRatio:.5625,aspectLabel:'9:16',orientation:'portrait',category:'social_story',baseSafeArea:{top:.06,right:.055,bottom:.06,left:.055},recommendedGrid:{kind:'hybrid',columnRange:[4,6],rowRange:[10,16]},aliases:['story_9_16','Story','Stories','1080x1920','9:16']});
export const PRESENTATION_FULL_HD:FormatDefinition={id:'presentation_full_hd',label:'Apresentação Full HD 16:9',usage:'presentation',width:1920,height:1080,aspectRatio:16/9,aspectLabel:'16:9',orientation:'landscape',category:'presentation',baseSafeArea:{top:.06,right:.07,bottom:.06,left:.07},recommendedGrid:{kind:'column',columnRange:[8,12],rowRange:[6,10]},aliases:['landscape_16_9','Presentation','Apresentação','1920x1080','16:9'],metadata:{recommended:true,presentation:true}};
export const META_ADS_SQUARE:FormatDefinition={...GENERIC_SQUARE_1080,id:'meta_ads_square',label:'Meta Ads — Quadrado 1:1',platform:'meta',usage:'advertising',commonPlacements:['Facebook Feed','Instagram Feed','Meta Ads square placements'],aliases:['Meta 1:1','Meta Square','Quadrado Meta','1080x1080','1:1'],metadata:{recommended:true,advertising:true}};
export const META_ADS_FEED_PORTRAIT:FormatDefinition={...GENERIC_PORTRAIT_1080_1350,id:'meta_ads_feed_portrait',label:'Meta Ads — Vertical Feed 4:5',platform:'meta',usage:'advertising',commonPlacements:['Instagram Feed','Facebook Feed','Feed portrait advertising'],aliases:['Meta 4:5','Meta Feed Vertical','Vertical Feed','1080x1350','4:5'],metadata:{recommended:true,advertising:true}};
export const META_ADS_STORY_REELS:FormatDefinition={...GENERIC_VERTICAL_1080_1920,id:'meta_ads_story_reels',label:'Meta Ads — Vertical 9:16',platform:'meta',usage:'advertising',baseSafeArea:{top:.06,right:.055,bottom:.06,left:.055},platformInsets:[{id:'meta_story_reels_chrome',insets:{top:.04,right:.015,bottom:.08,left:.015},configurable:true}],commonPlacements:['Instagram Stories','Facebook Stories','Instagram Reels','Facebook Reels'],aliases:['Meta 9:16','Reels','Story Meta','1080x1920','9:16'],metadata:{recommended:true,advertising:true}};
export const META_ADS_LANDSCAPE:FormatDefinition={id:'meta_ads_landscape',label:'Meta Ads — Horizontal 1.91:1',platform:'meta',usage:'advertising',width:1200,height:628,aspectRatio:1200/628,aspectLabel:'1.91:1',orientation:'landscape',category:'social_landscape',baseSafeArea:{top:.06,right:.055,bottom:.06,left:.055},recommendedGrid:{kind:'column',columnRange:[8,12],rowRange:[6,8]},commonPlacements:['Facebook Feed landscape','Meta advertising landscape','Link/image ads where landscape format is appropriate'],aliases:['Meta 1.91:1','Meta Horizontal','Landscape Meta','1200x628','1.91:1'],metadata:{recommended:true,advertising:true}};
const definitions=[GENERIC_SQUARE_1080,GENERIC_PORTRAIT_1080_1350,GENERIC_VERTICAL_1080_1920,PRESENTATION_FULL_HD,META_ADS_SQUARE,META_ADS_FEED_PORTRAIT,META_ADS_STORY_REELS,META_ADS_LANDSCAPE];
export const FORMAT_REGISTRY:Record<string,FormatDefinition>=Object.fromEntries(definitions.map(format=>[format.id,format]));
export const META_ADS_FAMILY:FormatFamily={id:'meta_ads_family',label:'Meta Ads Campaign',platform:'meta',variants:[META_ADS_SQUARE.id,META_ADS_FEED_PORTRAIT.id,META_ADS_STORY_REELS.id,META_ADS_LANDSCAPE.id]};
export const FORMAT_FAMILIES:Record<string,FormatFamily>={[META_ADS_FAMILY.id]:META_ADS_FAMILY};
const normalize=(v:string)=>v.trim().toLowerCase().replace(/[×]/g,'x').replace(/\s+/g,' ');
const orientation=(w:number,h:number):Orientation=>w===h?'square':w>h?'landscape':'portrait';
const contextual=(matches:FormatDefinition[],context?:FormatContext)=>{const platform=normalize(context?.platform??'');if(platform){const exact=matches.find(item=>normalize(item.platform??'')===platform);if(exact)return exact}return matches.find(item=>!item.platform)??matches[0]};
export const resolveFormatDefinition=(value:string|{width:number;height:number;id?:string;category?:FormatDefinition['category']},context?:FormatContext,limits={min:64,max:16384}):FormatDefinition=>{
  if(typeof value==='object'){
    if(!Number.isInteger(value.width)||!Number.isInteger(value.height)||value.width<limits.min||value.height<limits.min||value.width>limits.max||value.height>limits.max)throw new Error('Invalid custom format dimensions.');
    const ratio=value.width/value.height;const custom:CustomFormatDefinition={id:value.id??`custom_${value.width}x${value.height}`,label:`Custom ${value.width}×${value.height}`,width:value.width,height:value.height,aspectRatio:ratio,derivedAspectRatio:ratio,aspectLabel:`${value.width}:${value.height}`,orientation:orientation(value.width,value.height),category:'custom',baseSafeArea:inset(.06),recommendedGrid:{kind:'hybrid',columnRange:[4,12],rowRange:[6,16]},aliases:[],metadata:{}};return custom;
  }
  const query=normalize(value),direct=FORMAT_REGISTRY[query];if(direct)return structuredClone(direct);
  const aliasMatches=definitions.filter(item=>normalize(item.label)===query||item.aliases.some(alias=>normalize(alias)===query));if(aliasMatches.length)return structuredClone(contextual(aliasMatches,context));
  const dimensions=query.match(/(\d{2,5})\s*x\s*(\d{2,5})/);if(dimensions){const width=Number(dimensions[1]),height=Number(dimensions[2]),matches=definitions.filter(item=>item.width===width&&item.height===height);if(matches.length)return structuredClone(contextual(matches,context));return resolveFormatDefinition({width,height},context,limits)}
  throw new Error(`Unknown format: ${value}`);
};
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
export const resolveCanvas=(format:FormatDefinition,policy?:Partial<SafeAreaPolicy>):CanvasSpec=>{const safe={top:Math.max(format.baseSafeArea.top,policy?.minimum?.top??0),right:Math.max(format.baseSafeArea.right,policy?.minimum?.right??0),bottom:Math.max(format.baseSafeArea.bottom,policy?.minimum?.bottom??0),left:Math.max(format.baseSafeArea.left,policy?.minimum?.left??0)};const max=policy?.maximum;if(max){safe.top=Math.min(safe.top,max.top);safe.right=Math.min(safe.right,max.right);safe.bottom=Math.min(safe.bottom,max.bottom);safe.left=Math.min(safe.left,max.left)}for(const platform of policy?.platformInsets??[]){safe.top+=platform.insets.top;safe.right+=platform.insets.right;safe.bottom+=platform.insets.bottom;safe.left+=platform.insets.left}return{width:format.width,height:format.height,aspectRatio:format.aspectRatio,orientation:format.orientation,safeArea:safe,contentArea:{x:clamp(safe.left),y:clamp(safe.top),width:clamp(1-safe.left-safe.right),height:clamp(1-safe.top-safe.bottom)}}};
export const normalizedToPixel=(rect:NormalizedRect,canvas:Pick<CanvasSpec,'width'|'height'>):PixelRect=>{const x=Math.round(rect.x*canvas.width),y=Math.round(rect.y*canvas.height);return{x,y,width:Math.max(0,Math.min(canvas.width-x,Math.round(rect.width*canvas.width))),height:Math.max(0,Math.min(canvas.height-y,Math.round(rect.height*canvas.height)))}};
export const pixelToNormalized=(rect:PixelRect,canvas:Pick<CanvasSpec,'width'|'height'>):NormalizedRect=>({x:rect.x/canvas.width,y:rect.y/canvas.height,width:rect.width/canvas.width,height:rect.height/canvas.height});
