import type {BrandDNA} from '../brand-intelligence/index.js';
import type {CanvasSpec,LayoutContentBlock,TypographyScale,TypographyToken} from './types.js';
const roles:TypographyToken['role'][]=['display','headline','subheadline','body','data','cta','caption','legal'];
export const resolveTypographyScale=(canvas:CanvasSpec,brand?:BrandDNA,expression=''):TypographyScale=>{
  const short=Math.min(canvas.width,canvas.height),ratio=/dramatic|expressive|oversized/i.test(expression)?1.32:1.22,base=Math.max(14,Math.round(short*.017)),factors=[ratio**4,ratio**3,ratio**2,1,ratio**2,ratio,1/ratio,1/(ratio**1.5)];
  const tokens:TypographyToken[]=roles.map((role,i)=>{const preferred=Math.round(base*factors[i]);return{role,minSize:Math.max(9,Math.round(preferred*.72)),preferredSize:preferred,maxSize:Math.round(preferred*1.25),lineHeightRatio:['display','headline','data'].includes(role)?1.02:1.35,trackingRange:['display','headline'].includes(role)?[-.03,.02]:[0,.04],maxLines:role==='headline'?4:role==='legal'?8:6,weightRole:['display','headline','data'].includes(role)?'emphasis':'regular'}});
  const substitution=brand?.typographySystem?.roles.some(r=>r.fallbackStrategy?.substitutionRequired);return{ratio,baseSize:base,tokens,fontResolutionStatus:substitution?'fallback':brand?.typographySystem?'approved':'unresolved'};
};
export interface TextMeasureInput {text:string;fontSize:number;boxWidth:number;lineHeightRatio:number;role:string;language?:string}
export interface TextMeasurement {estimatedLines:number;estimatedHeight:number;overflow:boolean}
export interface TextMeasurementProvider {measure(input:TextMeasureInput):TextMeasurement}
export class HeuristicTextMeasurer implements TextMeasurementProvider{measure(i:TextMeasureInput){const averageChar=i.fontSize*(i.role==='headline'?.56:.5),chars=Math.max(1,Math.floor(i.boxWidth/averageChar)),words=i.text.trim().split(/\s+/);let lines=1,current=0;for(const word of words){if(current+word.length+1>chars){lines++;current=word.length}else current+=word.length+1}return{estimatedLines:lines,estimatedHeight:lines*i.fontSize*i.lineHeightRatio,overflow:false}}}
export class BrowserCanvasTextMeasurer implements TextMeasurementProvider{constructor(private context:{measureText(text:string):{width:number}}){}measure(i:TextMeasureInput){const width=this.context.measureText(i.text).width,lines=Math.max(1,Math.ceil(width/i.boxWidth));return{estimatedLines:lines,estimatedHeight:lines*i.fontSize*i.lineHeightRatio,overflow:false}}}
export const estimateTextFit=(block:LayoutContentBlock,text:string,box:{width:number;height:number},token:TypographyToken,canvas:CanvasSpec,measurer:TextMeasurementProvider=new HeuristicTextMeasurer())=>{for(let size=token.preferredSize;size>=token.minSize;size--){const m=measurer.measure({text,fontSize:size,boxWidth:box.width*canvas.width,lineHeightRatio:token.lineHeightRatio,role:block.role});if(m.estimatedLines<=Math.max(block.maxLines??token.maxLines,token.maxLines)&&m.estimatedHeight<=box.height*canvas.height)return{fits:true,size,lines:m.estimatedLines}}return{fits:false,size:token.minSize,lines:Infinity}};
