import {createHash} from 'node:crypto';
import {buildProductionFilename,buildProductionManifest,EXPORT_MAX_PACKAGE_MB,EXPORT_MAX_SINGLE_FILE_MB,EXPORT_POLICY_VERSION,EXPORT_PROFILES,EXPORT_SCHEMA_VERSION,fingerprintApprovedPackage,runProductionExportPreflight,type ExportFormat,type ProductionArtifactStore,type ProductionExportArtifact,type ProductionExportRequest,type ProductionExportSession,type RasterEncoder,type SelfContainedSvgExporter} from '../../domain/export-engine/index.js';
import type {GeneratedAssetStore} from '../../domain/image-assets/index.js';
import {buildProductionZip,buildProofPdf,inspectPdf} from '../../infrastructure/export-engine/index.js';

type ExportDependencies={assetStore:GeneratedAssetStore;artifactStore:ProductionArtifactStore;rasterEncoder:RasterEncoder;svgExporter:SelfContainedSvgExporter;maxSingleFileMb?:number;maxPackageMb?:number};
const sha=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
const mediaType:Record<ExportFormat,string>={png:'image/png',webp:'image/webp',pdf:'application/pdf',svg:'image/svg+xml',zip:'application/zip'};
const folder=(format:ExportFormat)=>format==='png'?'PNG':format==='webp'?'WebP':format==='pdf'?'PDF':format==='svg'?'SVG':'';

export const createProductionExport=async(request:ProductionExportRequest,deps:ExportDependencies):Promise<ProductionExportSession>=>{
  const pkg=request.visualApprovedPackage,profileName=request.profile??'social_png',profile=EXPORT_PROFILES[profileName],formats=[...new Set([...request.formats,...(request.includePdf?['pdf' as const]:[]),...(request.includeZip?['zip' as const]:[])])],fingerprint=fingerprintApprovedPackage({...request,formats}),existing=request.existingSession;
  if(existing?.inputFingerprint===fingerprint&&existing.artifacts.every(artifact=>artifact.backingRef)&&await Promise.all(existing.artifacts.map(artifact=>deps.artifactStore.exists(artifact.backingRef!,request.projectId))).then(results=>results.every(Boolean)))return{...existing,cacheHit:true};
  const preflight=await runProductionExportPreflight(request,deps.assetStore);if(!preflight.passed)throw new Error(`Production export blocked: ${preflight.blockers.join(', ')}`);
  const selectedScenes=pkg.renderSession.renderDocument.scenes.filter(scene=>!request.sceneIds||request.sceneIds.includes(scene.sceneId)),canonicalByScene=new Map(pkg.canonicalArtifacts.map(artifact=>[artifact.sceneId,artifact])),active=pkg.generatedAssetSession?.activeGeneratedAssets??pkg.generatedAssetSession?.generatedAssets??[],historicalIds=new Set(pkg.generatedAssetSession?.historicalGeneratedAssets?.map(asset=>asset.id)??[]),artifacts:ProductionExportArtifact[]=[],payloads=new Map<string,Uint8Array>(),pngPages:Array<{png:Uint8Array;width:number;height:number}>=[],warnings=[...preflight.warnings];
  const resolveAsset=async(assetId:string)=>{if(historicalIds.has(assetId))throw new Error(`Historical asset cannot be exported: ${assetId}`);const asset=pkg.finalAssets.assets.find(item=>item.id===assetId);if(!asset?.backingRef)throw new Error(`Asset backing missing: ${assetId}`);const bytes=await deps.assetStore.get(asset.backingRef,request.projectId);if(!bytes)throw new Error(`Asset backing missing: ${assetId}`);return{bytes,mediaType:asset.mediaType}};
  const save=async(input:{format:ExportFormat;filename:string;bytes:Uint8Array;sceneId?:string;width?:number;height?:number;canonicalChecksum:string;warnings?:string[]})=>{const limit=(deps.maxSingleFileMb??EXPORT_MAX_SINGLE_FILE_MB)*1024*1024;if(input.bytes.length===0||input.bytes.length>limit)throw new Error(`Export file size invalid: ${input.filename}`);const checksum=sha(input.bytes),artifactId=`export_${checksum.slice(0,20)}`,backingRef=await deps.artifactStore.put({projectId:request.projectId,exportFingerprint:fingerprint,artifactId,filename:input.filename,bytes:input.bytes,mediaType:mediaType[input.format],checksum}),artifact:ProductionExportArtifact={artifactId,projectId:request.projectId,sceneId:input.sceneId,format:input.format,filename:input.filename,mediaType:mediaType[input.format],width:input.width,height:input.height,checksum,byteSize:input.bytes.length,backingRef,source:{visualApprovedPackageFingerprint:fingerprint,renderSessionId:pkg.renderSession.sessionId,canonicalArtifactChecksum:input.canonicalChecksum},status:'ready',warnings:input.warnings??[],createdAt:new Date().toISOString(),retentionClass:'standard'};artifacts.push(artifact);payloads.set(artifactId,input.bytes);return artifact};
  for(const [index,scene] of selectedScenes.entries()){const canonical=canonicalByScene.get(scene.sceneId);if(!canonical)throw new Error(`Canonical artifact missing for ${scene.sceneId}`);const selfContained=await deps.svgExporter.export(canonical.svg,resolveAsset),png=await deps.rasterEncoder.encodePng(new TextDecoder().decode(selfContained.bytes),scene.width,scene.height),pngInfo=await deps.rasterEncoder.inspect(png);if(pngInfo.format!=='png'||pngInfo.width!==scene.width||pngInfo.height!==scene.height)throw new Error('PNG dimensions do not match approved canvas.');pngPages.push({png,width:scene.width,height:scene.height});const placement=pkg.reviewedDesignPackage.layoutPlan.format.id,base={projectSlug:request.projectSlug??request.projectId,placement,width:scene.width,height:scene.height,index,total:selectedScenes.length};if(formats.includes('png'))await save({format:'png',filename:buildProductionFilename({...base,format:'png'}),bytes:png,sceneId:scene.sceneId,width:scene.width,height:scene.height,canonicalChecksum:canonical.checksum});if(formats.includes('webp')){const webp=await deps.rasterEncoder.encodeWebp(png,profile.webpQuality),info=await deps.rasterEncoder.inspect(webp);if(info.format!=='webp'||info.width!==scene.width||info.height!==scene.height)throw new Error('WebP dimensions do not match approved canvas.');await save({format:'webp',filename:buildProductionFilename({...base,format:'webp'}),bytes:webp,sceneId:scene.sceneId,width:scene.width,height:scene.height,canonicalChecksum:canonical.checksum})}if(formats.includes('svg'))await save({format:'svg',filename:buildProductionFilename({...base,format:'svg'}),bytes:selfContained.bytes,sceneId:scene.sceneId,width:scene.width,height:scene.height,canonicalChecksum:canonical.checksum,warnings:selfContained.warnings})}
  if(formats.includes('pdf')){const pdf=await buildProofPdf(pngPages),inspection=await inspectPdf(pdf);if(inspection.pageCount!==selectedScenes.length||inspection.ratios.some((ratio,index)=>Math.abs(ratio-selectedScenes[index]!.width/selectedScenes[index]!.height)>.0001))throw new Error('PDF validation failed.');await save({format:'pdf',filename:`${buildProductionFilename({projectSlug:request.projectSlug??request.projectId,placement:'proof',format:'pdf'})}`,bytes:pdf,canonicalChecksum:sha(new TextEncoder().encode(pkg.canonicalArtifacts.map(artifact=>artifact.checksum).join(':')))})}
  const manifest=(request.includeManifest??profile.manifest)||formats.includes('zip')?buildProductionManifest(request.projectId,fingerprint,artifacts,pkg):undefined;
  let packageArtifact:ProductionExportArtifact|undefined;if(formats.includes('zip')){const entries=artifacts.map(artifact=>({path:`${folder(artifact.format)}/${artifact.filename}`,bytes:payloads.get(artifact.artifactId)!}));if(manifest)entries.push({path:'manifest.json',bytes:new TextEncoder().encode(JSON.stringify(manifest,null,2))});const zip=buildProductionZip(entries);if(zip.length>(deps.maxPackageMb??EXPORT_MAX_PACKAGE_MB)*1024*1024)throw new Error('Export package exceeds configured size limit.');packageArtifact=await save({format:'zip',filename:`${request.projectSlug?request.projectSlug.replace(/[^a-zA-Z0-9_-]+/g,'-'):'project'}_production-package.zip`,bytes:zip,canonicalChecksum:sha(new TextEncoder().encode(pkg.canonicalArtifacts.map(artifact=>artifact.checksum).join(':')))})}
  return{schemaVersion:EXPORT_SCHEMA_VERSION,sessionId:`export_${fingerprint.slice(0,20)}`,projectId:request.projectId,createdAt:new Date().toISOString(),inputFingerprint:fingerprint,profile:profileName,artifacts,manifest,packageArtifact,status:'ready',warnings,cost:{aiUsd:0},sourceVersions:{export:EXPORT_SCHEMA_VERSION,policy:EXPORT_POLICY_VERSION,...pkg.renderSession.sourceVersions},cacheHit:false,storageKind:deps.artifactStore.kind};
};
